<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Help us with your city_city_name</name>
   <tag></tag>
   <elementGuidId>be1c63e0-7044-41e2-9300-0bc3dce42949</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#city_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='city_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>817658f9-d626-47f9-8683-95653dba0583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>city_name</value>
      <webElementGuid>8e39c1fa-9257-4207-8d24-ba267d402776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city_name</value>
      <webElementGuid>c21c5885-6916-42e0-840b-f85e076b6084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input animate_label</value>
      <webElementGuid>d8d0eb15-762f-4a8e-8df2-e54f308dd1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7e7c5c90-eb1a-48be-85c2-e61cafb7334d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>2e10cf62-770c-4f71-acb9-3a1ac5069270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocusout</name>
      <type>Main</type>
      <value>getQuoteCity(this.value)</value>
      <webElementGuid>97eabae2-ffef-4a5e-9d65-201c066fce60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;city_name&quot;)</value>
      <webElementGuid>1497066c-8277-4409-b697-56fba5c8480a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='city_name']</value>
      <webElementGuid>072db166-171c-41a5-8565-36aba6b2b909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='care-quote-box']/div[3]/div[2]/div/div/input</value>
      <webElementGuid>414208f2-9f17-4882-92ab-c7ddeac1d41b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>ad178c7b-39bf-4115-95b0-a14092295c39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'city_name' and @name = 'city_name' and @type = 'text']</value>
      <webElementGuid>27b59369-cbba-47eb-8baf-79a73acee6e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
