<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select age5-17 Years18-24 Years25-35_2c9cec</name>
   <tag></tag>
   <elementGuidId>a21460e0-7ca3-4673-bdef-6de4f8ee6943</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;ageGroupOfEldestMember&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='ageGroupOfEldestMember']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3962d22c-62cb-4c1a-a638-ff8cb8063513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>eldest_member lozad</value>
      <webElementGuid>fdc904a3-b66b-48f2-a9c1-5d5bed485c1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ageGroupOfEldestMember</value>
      <webElementGuid>f41c2fa4-d652-48f4-a921-90a30f6b5f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-background-image</name>
      <type>Main</type>
      <value>https://www.careinsurance.com/rhicl/public/images/sem_dynamic/down-arrow.png</value>
      <webElementGuid>2fec37b1-b2a0-4f21-b64a-84adec9d1131</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>23b0534a-522e-4f4f-bd5e-23707eb6e7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>3b095384-f88a-4c78-bff5-958909c295e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select age5-17 Years18-24 Years25-35 Years36-40 Years41-45 Years46-50 Years51-55 Years56-60 Years61-65 Years66-70 Years71-75 Years76-80 Years>80 Years</value>
      <webElementGuid>e949d3e2-04a1-4431-8415-cfa79f890921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;care-quote-box&quot;)/div[@class=&quot;step2 Cr-PreQuote-InsuredDetails&quot;]/div[@class=&quot;form-group age_input&quot;]/select[@class=&quot;eldest_member lozad&quot;]</value>
      <webElementGuid>0ea2b54b-0366-4217-97a9-334ab8489a24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='ageGroupOfEldestMember']</value>
      <webElementGuid>9bc1ed06-cfb3-415d-8ad7-3518f1bdfa64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='care-quote-box']/div[2]/div[3]/select</value>
      <webElementGuid>55ef01a3-2d82-46ed-9793-aad2aa52698b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mother'])[1]/following::select[1]</value>
      <webElementGuid>0359ff19-5988-46cc-b211-170a8086555a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Father'])[1]/following::select[1]</value>
      <webElementGuid>77c34262-d7ea-4e3f-8676-281df35b58b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::select[1]</value>
      <webElementGuid>257c10a7-58f6-4233-b1cf-2e8050c672ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help us with your city'])[1]/preceding::select[1]</value>
      <webElementGuid>2842c822-2eee-4598-97e6-1e49782e15f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/select</value>
      <webElementGuid>12660eb9-6f85-4b31-b252-0fcbce5dfc2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ageGroupOfEldestMember' and (text() = 'Select age5-17 Years18-24 Years25-35 Years36-40 Years41-45 Years46-50 Years51-55 Years56-60 Years61-65 Years66-70 Years71-75 Years76-80 Years>80 Years' or . = 'Select age5-17 Years18-24 Years25-35 Years36-40 Years41-45 Years46-50 Years51-55 Years56-60 Years61-65 Years66-70 Years71-75 Years76-80 Years>80 Years')]</value>
      <webElementGuid>aa1ae713-1c42-4607-99fe-003b6fc77054</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
