<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Views_img-fluid rounded main-image</name>
   <tag></tag>
   <elementGuidId>6ef1aa2d-fd46-4f8b-92ff-a5b9ec77f7bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-fluid.rounded.main-image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='5 Kinds of Foods and Beverages Diabetic People Must Avoid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>acfbb8eb-59a1-4266-a02a-03e84cf9a13f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid rounded main-image</value>
      <webElementGuid>bd0c89fd-6e28-49b9-b111-aeaf5db82310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>789</value>
      <webElementGuid>fc011587-4a1c-4f56-b527-3b207c46855a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>330</value>
      <webElementGuid>28613f95-1aff-49e6-8daa-e5c184b11bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.careinsurance.com/upload_master/media/posts/July2023/organ-transplant.webp</value>
      <webElementGuid>71e5e62b-37df-4572-9c71-96c864e052ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>The Ultimate Guide to Organ Donation and Transplantation</value>
      <webElementGuid>33fe2dbc-87b5-424b-8764-7492da324705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>The Ultimate Guide to Organ Donation and Transplantation</value>
      <webElementGuid>c66f9f3c-241d-40ff-b248-d12ed5ffefd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;bg_color&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;blog_detail_body&quot;]/div[@class=&quot;blog_detail_body_left&quot;]/picture[1]/img[@class=&quot;img-fluid rounded main-image&quot;]</value>
      <webElementGuid>bed6b3d5-6443-4304-acb5-0e2c689d5d1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='The Ultimate Guide to Organ Donation and Transplantation']</value>
      <webElementGuid>2717497e-cc7d-44ae-9512-1bab2f4e37be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/picture/img</value>
      <webElementGuid>ba8e0f8c-e3c9-4a59-9408-9eefd4388b29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.careinsurance.com/upload_master/media/posts/July2023/organ-transplant.webp' and @alt = 'The Ultimate Guide to Organ Donation and Transplantation' and @title = 'The Ultimate Guide to Organ Donation and Transplantation']</value>
      <webElementGuid>722e3add-90b4-436d-894e-89b5b7ce28c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
