<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Card Number_card_number_iframe_70abW_8456c3</name>
   <tag></tag>
   <elementGuidId>5655064e-f9be-42a0-b219-a1f015eb1c49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;card_number_iframe_70abWez9KEZe8ISr&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='card_number_iframe_70abWez9KEZe8ISr']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a3ebf6ff-9d8d-4be1-b0e8-b0838d2d544e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.juspay.in/iframe-element?detected_origin=www.careinsurance.com&amp;version=3.1</value>
      <webElementGuid>01f39271-ca34-4180-831a-62a11b31f656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f460cedd-cd4d-4efa-9a67-45f8370a658e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7aea3150-5cc8-4b2c-92dc-46b0ef70376e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>3a946299-7ec6-4521-890b-6b72ee1a0f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card_number_iframe_70abWez9KEZe8ISr</value>
      <webElementGuid>4eeb0528-9808-4b12-8442-3cca3cd9fb5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card_number_iframe</value>
      <webElementGuid>2f944b6b-8d2e-47c3-9b34-372a3c63f7c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;credit_card_form&quot;)/div[@class=&quot;payment_input_box&quot;]/div[@class=&quot;content_padding&quot;]/div[@class=&quot;form-horizontal offset4 span4&quot;]/div[@class=&quot;card_number_div&quot;]/iframe[@class=&quot;card_number_iframe&quot;]</value>
      <webElementGuid>f833a3d5-63ac-42d3-bf3e-f2e6458cf86c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='card_number_iframe_70abWez9KEZe8ISr']</value>
      <webElementGuid>b0a3aee0-4079-49e1-9aa4-750d2e0887aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='credit_card_form']/div/div/div[2]/div/iframe</value>
      <webElementGuid>e06afca3-1483-47a9-bcd0-a9d43e1ecd4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>d84e4c14-ef35-45b7-89d1-8efa053c6659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://api.juspay.in/iframe-element?detected_origin=www.careinsurance.com&amp;version=3.1' and @name = 'card_number_iframe_70abWez9KEZe8ISr']</value>
      <webElementGuid>f1d86c71-b37f-444e-91ee-631652d0be56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
