<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(id(, , card_number, , ))_card_number</name>
   <tag></tag>
   <elementGuidId>6ca0376d-c385-4bbe-b9f2-493b6a39880a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='card_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>234763b6-5918-4c04-9561-35c24b6de9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>fe30d417-09ef-4d09-9991-7cb436920435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>xxxx-xxxx-xxxx-xxxx</value>
      <webElementGuid>4c51f311-9615-4c0f-b192-9196cb0d82ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card_number</value>
      <webElementGuid>3a7be797-08a8-4b55-81ed-9d3b04174636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card_number</value>
      <webElementGuid>8539cc88-9dcb-4c23-8f0f-b2938384ab78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card_number</value>
      <webElementGuid>18b7a8ef-b070-4dae-9a11-05e4621bd73f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5697107d-18c8-4fb4-ac14-6d3243f0b597</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form_id</name>
      <type>Main</type>
      <value>#credit_card_form</value>
      <webElementGuid>63886865-0d87-4d0c-8956-a5db8cdfc7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return isOnlyNumeric(event);</value>
      <webElementGuid>1106095c-5a95-4044-beb0-b1bd5654f7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>3b8886b8-e9c6-41b6-b494-e24344be301a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-merchant_id</name>
      <type>Main</type>
      <value>religare</value>
      <webElementGuid>5e78558d-00d0-4e3f-bf53-735713bd91e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card_number&quot;)</value>
      <webElementGuid>c0acccd2-ba62-4030-8e0b-c4d780a8d4b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Positive Journey/Page_Care Payment/iframe_Card Number_card_number_iframe_70abW_8456c3</value>
      <webElementGuid>5d0d728a-d837-41c2-88ca-fb8024436718</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='card_number']</value>
      <webElementGuid>5442bed4-a593-44c7-9495-6e2a072c59d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b7f2c34b-d33c-4c85-9607-57163376c539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @placeholder = 'xxxx-xxxx-xxxx-xxxx' and @name = 'card_number' and @id = 'card_number']</value>
      <webElementGuid>dbb5dff9-9eb7-4ad2-a6f9-3896a74b15a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
