<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , allincall-chat-box, , _706759</name>
   <tag></tag>
   <elementGuidId>428d8930-b45f-495e-bc31-2ddec04129b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='allincall-chat-box']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#allincall-chat-box</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a5362c01-247e-4ebb-84e1-241251ae66bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>allincall-chat-box</value>
      <webElementGuid>062ad94a-269d-4821-8d6e-e12de24d32f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>microphone</value>
      <webElementGuid>48bdc808-3354-4d44-9455-cd4b169ebedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://chatprod.careinsurance.com/chat/index/?id=1&amp;name=uat&amp;theme=4&amp;easychat_window_location=https%3A%2F%2Fwww.careinsurance.com%2Fcontact-us.html&amp;form_assist_id=&amp;do_not_disturb=&amp;is_lead_generation=false&amp;page_category=&amp;meta_data=uzXhujYm0xJP3d00.Ajb23wm63fcl1EpTmlLhpglO5wft1Jwa9QqdfxcIMcrLlFIRcyRwXaOD6d8FbzuwUBazZaG3tPCD9eIU496S9RE1JqJctfwOc1ANhAJ+L2QTWkYvWerJi5f45wN6H2ved+sfwbr/4Ybiq74SiqVlt/eTmsOfpcW2ttx3+/lUAaIBINQKev96kdNiJcPfLtDeSCBMKCSpIdbKfJbONDye4220g+UPQ8I6Ep7/QqGV7CM=.PhLBcS59ODVlalgYxdqTWw==&amp;easychat_intent_name=&amp;is_web_landing_allowed=false&amp;campaign_link_query_id=INTENT_ID</value>
      <webElementGuid>07a1d33e-a73e-4403-a237-fbcd4b1ab0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>animate__animated animate__slideInUp</value>
      <webElementGuid>7db919d3-0479-45e2-b4d0-a597ff46a076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;allincall-chat-box&quot;)</value>
      <webElementGuid>3b41abdd-41e2-4b3c-866a-ab58e93685d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='allincall-chat-box']</value>
      <webElementGuid>f517eaed-7f1f-429c-aa10-fd564627112d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>f10b53c6-8dad-4b60-a7ba-6f451fee3ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'allincall-chat-box' and @src = 'https://chatprod.careinsurance.com/chat/index/?id=1&amp;name=uat&amp;theme=4&amp;easychat_window_location=https%3A%2F%2Fwww.careinsurance.com%2Fcontact-us.html&amp;form_assist_id=&amp;do_not_disturb=&amp;is_lead_generation=false&amp;page_category=&amp;meta_data=uzXhujYm0xJP3d00.Ajb23wm63fcl1EpTmlLhpglO5wft1Jwa9QqdfxcIMcrLlFIRcyRwXaOD6d8FbzuwUBazZaG3tPCD9eIU496S9RE1JqJctfwOc1ANhAJ+L2QTWkYvWerJi5f45wN6H2ved+sfwbr/4Ybiq74SiqVlt/eTmsOfpcW2ttx3+/lUAaIBINQKev96kdNiJcPfLtDeSCBMKCSpIdbKfJbONDye4220g+UPQ8I6Ep7/QqGV7CM=.PhLBcS59ODVlalgYxdqTWw==&amp;easychat_intent_name=&amp;is_web_landing_allowed=false&amp;campaign_link_query_id=INTENT_ID']</value>
      <webElementGuid>0d5702a0-bac9-4693-8548-cd6a4a95cf52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
