<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Download the Care Health Insurance - Cu_d02ecd</name>
   <tag></tag>
   <elementGuidId>2eb85d38-4a2d-4de4-8b75-9ed42ed9ab96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='app_download']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.app_iocn > img.lozad</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>84a35565-ec72-4ad2-8f7f-bd79ee86dcad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>254</value>
      <webElementGuid>d01fc124-c3f1-411d-9a69-3eafc59e3a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>451c0145-440b-442a-8b7c-5fc608f4c8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lozad</value>
      <webElementGuid>6d8a44ed-d7ff-4df1-a619-c6dcbf032d88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>app_download</value>
      <webElementGuid>1c8ecb14-8ced-4f25-862b-c99f5391e283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>app_download</value>
      <webElementGuid>bea8a74f-071f-4c2b-8e9b-0075ad3cd626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.careinsurance.com/assets/images/shpimg/Mobile_App.png</value>
      <webElementGuid>07277129-eb3a-44a6-bd05-29ca59a6918a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.careinsurance.com/assets/images/shpimg/Mobile_App.png</value>
      <webElementGuid>589bd91b-bd6b-4b9a-836d-ed7e9c571f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5973b1c0-352e-4254-a12f-3a5b1df71a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cards_show Chrome_view&quot;]/section[@class=&quot;support_cont&quot;]/div[@class=&quot;custom_container&quot;]/div[@class=&quot;support_details_section&quot;]/div[@class=&quot;support_method&quot;]/div[@class=&quot;step_container&quot;]/div[@class=&quot;help_details flex_div&quot;]/div[@class=&quot;app_download&quot;]/div[@class=&quot;ios_android_icon&quot;]/p[@class=&quot;app_iocn&quot;]/img[@class=&quot;lozad&quot;]</value>
      <webElementGuid>34a8ad1c-5453-4bf5-8e35-a2c5b76bc901</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='app_download']</value>
      <webElementGuid>a2ada16e-1efd-4be3-863e-0d3abe6efd80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/img</value>
      <webElementGuid>25fd2aa9-9011-490a-958c-52f2f2cdc52c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'app_download' and @title = 'app_download' and @src = 'https://www.careinsurance.com/assets/images/shpimg/Mobile_App.png']</value>
      <webElementGuid>e08b28eb-b953-4124-96d0-7c2e6844672b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
