<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_1 Crore Health Plan</name>
   <tag></tag>
   <elementGuidId>c6396ee4-b6dc-4356-a183-ec3e229dbf47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='selected_drop_down']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selected_drop_down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>d1ffaa6d-5aef-4691-b62b-9755a3a39fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected_drop_down active</value>
      <webElementGuid>ed008c30-f415-4ef3-b9d7-faccad59ddc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selected_drop_down</value>
      <webElementGuid>ab1d1dff-fb34-4236-a735-e24cfd1c5ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-href</name>
      <type>Main</type>
      <value>https://www.careinsurance.com/product/care-advantage</value>
      <webElementGuid>ff604f55-f132-4ddc-b4b6-b34907227e9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 Crore Health Plan</value>
      <webElementGuid>3c3267d9-d77b-45ff-bcd0-04e3043f52f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selected_drop_down&quot;)</value>
      <webElementGuid>a6b70026-8d77-4093-87fb-1185783cefd3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='selected_drop_down']</value>
      <webElementGuid>725cdcec-4d3f-4c72-bdce-8472943ddc93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='quote-form-step-1']/div[2]/ul/li</value>
      <webElementGuid>2363b66f-d101-49af-ad31-102e91a3b1c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Mobile Number'])[2]/following::li[1]</value>
      <webElementGuid>458a7249-842c-44a1-82b0-cd43cf3d349f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Claim Support'])[1]/following::li[1]</value>
      <webElementGuid>e66360f7-af7b-4d75-bcb4-711f09a2608c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Individual Health Insurance'])[1]/preceding::li[2]</value>
      <webElementGuid>fd263708-ccdd-494b-9a73-e054a4dd86f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Health Insurance for Senior Citizens'])[1]/preceding::li[3]</value>
      <webElementGuid>ff03e800-3ca1-4342-a05c-573f26eff371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1 Crore Health Plan']/parent::*</value>
      <webElementGuid>ce0d9674-aef5-42a5-ba6d-4e8718b431ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/ul/li</value>
      <webElementGuid>e56b035c-7461-49ad-a869-4497f23961ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'selected_drop_down' and (text() = '1 Crore Health Plan' or . = '1 Crore Health Plan')]</value>
      <webElementGuid>8aef9add-58a8-4120-a66d-fb955f603150</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
