<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Help us with your city_city_name</name>
   <tag></tag>
   <elementGuidId>ad6e8afb-8377-463d-9aa2-a7e9ca339652</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#city_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='city_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad49f69d-0796-472f-9b4d-682d7c481662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>city_name</value>
      <webElementGuid>a651c061-670f-40c5-99fe-98300c864952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city_name</value>
      <webElementGuid>be77b7e1-1208-4663-abac-a3f77e323bc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input animate_label</value>
      <webElementGuid>8e93d70c-322b-4169-bf7b-ed997bd5f5ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d08b1b85-f883-40de-b331-f8379df12f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>85c6dd9b-f331-4969-818b-458bae8645d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocusout</name>
      <type>Main</type>
      <value>getQuoteCity(this.value)</value>
      <webElementGuid>9cb1fb44-ff7b-4ba9-a91a-4ee8cdbaffe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;city_name&quot;)</value>
      <webElementGuid>7c6998cf-b777-4181-90a5-4a7caecf6891</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='city_name']</value>
      <webElementGuid>42eb3ef1-3ea2-44d1-8ae4-e2e7d4337d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='care-quote-box']/div[3]/div[2]/div/div/input</value>
      <webElementGuid>9e4617e4-530a-41c6-b033-c1f10cfd98ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>5d47573a-929b-4463-a48d-57d1488ac96a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'city_name' and @name = 'city_name' and @type = 'text']</value>
      <webElementGuid>eabea89c-4ce8-43d1-8720-4cf079f3b3af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
