<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select age5-17 Years18-24 Years25-35_2c9cec</name>
   <tag></tag>
   <elementGuidId>0d102be0-f1c3-4f41-9189-066540c9dfca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;ageGroupOfEldestMember&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='ageGroupOfEldestMember']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>09969929-a47e-4ded-8cc3-e4455958fe18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>eldest_member lozad</value>
      <webElementGuid>10a15a4a-da2a-41eb-9800-b8eb82a95def</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ageGroupOfEldestMember</value>
      <webElementGuid>7b0c96cb-7d31-4124-b25f-15e38622b053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-background-image</name>
      <type>Main</type>
      <value>https://www.careinsurance.com/rhicl/public/images/sem_dynamic/down-arrow.png</value>
      <webElementGuid>e5a7485e-825d-4407-9759-48d5aedfb8df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>89409d2e-8b69-4bff-89f7-7479a9d26652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>bf1495d0-a1b7-47a0-a69d-38763c00fb4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select age5-17 Years18-24 Years25-35 Years36-40 Years41-45 Years46-50 Years51-55 Years56-60 Years61-65 Years66-70 Years71-75 Years76-80 Years>80 Years</value>
      <webElementGuid>790482d4-43b9-4d67-a4dd-4fd47a0d4d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;care-quote-box&quot;)/div[@class=&quot;step2 Cr-PreQuote-InsuredDetails&quot;]/div[@class=&quot;form-group age_input&quot;]/select[@class=&quot;eldest_member lozad&quot;]</value>
      <webElementGuid>78db72e2-f1b8-4d3e-b25e-bb1796428dd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='ageGroupOfEldestMember']</value>
      <webElementGuid>56c16548-1b74-4356-ac60-b7948420e09b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='care-quote-box']/div[2]/div[3]/select</value>
      <webElementGuid>8d0e57c3-2174-46bc-acb5-56f95e131f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mother'])[1]/following::select[1]</value>
      <webElementGuid>d469ed5d-132e-4462-8e41-4c2727d72269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Father'])[1]/following::select[1]</value>
      <webElementGuid>f38daf2d-46b7-4e9f-9e13-bf9e87fba4f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::select[1]</value>
      <webElementGuid>f019f6db-e438-4208-8266-6cb1bb9f49f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help us with your city'])[1]/preceding::select[1]</value>
      <webElementGuid>b3a8ef65-8f51-4e70-93d4-61be0c8a0b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/select</value>
      <webElementGuid>332f962e-00b8-4f2d-8994-1e652b7c98ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ageGroupOfEldestMember' and (text() = 'Select age5-17 Years18-24 Years25-35 Years36-40 Years41-45 Years46-50 Years51-55 Years56-60 Years61-65 Years66-70 Years71-75 Years76-80 Years>80 Years' or . = 'Select age5-17 Years18-24 Years25-35 Years36-40 Years41-45 Years46-50 Years51-55 Years56-60 Years61-65 Years66-70 Years71-75 Years76-80 Years>80 Years')]</value>
      <webElementGuid>b4a890f4-cc42-495a-96f1-5854cec6efad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
