<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cancel Popup</name>
   <tag></tag>
   <elementGuidId>14ae2235-26c2-45a4-97db-745d19771678</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.Close</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@alt = 'Close' and @title = 'Close' and @src = 'https://www.careinsurance.com/cpproject/rhiclfrontend/assets/public/images/AB-Testing-Popup/cross-01.svg']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>id(&quot;survey_popup&quot;)/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ab2-modal-inner-content&quot;]/span[@class=&quot;close1 survey_close sec_popup exit_intent_close&quot;]/img[@class=&quot;Close&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bb2add66-9e6e-4573-9a8e-74e88c70ef28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>df61de3c-541c-4c09-bbc9-26fdf6cb7c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>93000e82-cae1-4587-99a3-84061e5ee4da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>4f0b3eb0-2199-4c84-9467-573eb5a1d138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>7d202792-36bd-4fb9-9e3b-109db2fa41c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>6eeea57f-9de5-4b73-870c-540fbdad0db5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>6e4dbff8-9da5-4283-b90a-49da1bcda558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.careinsurance.com/cpproject/rhiclfrontend/assets/public/images/AB-Testing-Popup/cross-01.svg</value>
      <webElementGuid>60b6eb2b-71dd-4f5e-a6ce-80d84816b7fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;survey_popup&quot;)/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ab2-modal-inner-content&quot;]/span[@class=&quot;close1 survey_close sec_popup exit_intent_close&quot;]/img[@class=&quot;Close&quot;]</value>
      <webElementGuid>b609e747-9d07-4aaa-8ac9-3293d0cc02f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='survey_popup']/div/div/span/img</value>
      <webElementGuid>a4617fdb-d11a-4bc9-83db-81903af1e82c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Close'])[3]</value>
      <webElementGuid>f7cf55f1-a6ac-4050-b965-2a709c000757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/span/img</value>
      <webElementGuid>f2a2be42-1543-4a97-bcd6-6fc357d72c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Close' and @title = 'Close' and @src = 'https://www.careinsurance.com/cpproject/rhiclfrontend/assets/public/images/AB-Testing-Popup/cross-01.svg']</value>
      <webElementGuid>606db419-a0b9-4e06-a101-762b5c4b44f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
