<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select age5-17 Years18-24 Years25-35_2c9cec</name>
   <tag></tag>
   <elementGuidId>ee0d27f3-efa0-4b15-a6ed-1d52970b6d9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='ageGroupOfEldestMember']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;ageGroupOfEldestMember&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d53b89a8-d10d-42b0-baf4-2cac94ca168d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>eldest_member lozad</value>
      <webElementGuid>7caf0cc4-e319-4d84-8da3-22b26af3f7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ageGroupOfEldestMember</value>
      <webElementGuid>9707abd6-3469-45d2-ab92-59ca93f2cf6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-background-image</name>
      <type>Main</type>
      <value>https://www.careinsurance.com/rhicl/public/images/sem_dynamic/down-arrow.png</value>
      <webElementGuid>2d7868e7-ab60-4cbb-9964-b6e5e5110b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1872f705-7f2d-4173-869b-85ae9b8d40d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>c6631f5f-cc50-4303-b1c6-16cf1b93762f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select age5-17 Years18-24 Years25-35 Years36-40 Years41-45 Years46-50 Years51-55 Years56-60 Years61-65 Years66-70 Years71-75 Years76-80 Years>80 Years</value>
      <webElementGuid>2e2a6983-3ff2-4c54-a260-2d5f34678a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;care-quote-box&quot;)/div[@class=&quot;step2 Cr-PreQuote-InsuredDetails&quot;]/div[@class=&quot;form-group age_input&quot;]/select[@class=&quot;eldest_member lozad&quot;]</value>
      <webElementGuid>5920da05-083b-4ab6-bf1a-dc761417ce7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='ageGroupOfEldestMember']</value>
      <webElementGuid>9b8967af-94ac-4544-a430-dcbbae42db37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='care-quote-box']/div[2]/div[3]/select</value>
      <webElementGuid>68bcef53-a958-4b05-8bad-9494c2f71614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mother'])[1]/following::select[1]</value>
      <webElementGuid>ab5104bc-95a5-44ef-a2b5-8963d78d1b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Father'])[1]/following::select[1]</value>
      <webElementGuid>a4be9f73-ca62-484b-a3c8-4e120e1c5173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::select[1]</value>
      <webElementGuid>664ac41a-e192-4508-a28a-52dfaec86241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help us with your city'])[1]/preceding::select[1]</value>
      <webElementGuid>05cbd842-a1b0-4a74-a49a-e7419918f299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/select</value>
      <webElementGuid>80aa2620-c6b7-4201-a4f0-0a7e730b62c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ageGroupOfEldestMember' and (text() = 'Select age5-17 Years18-24 Years25-35 Years36-40 Years41-45 Years46-50 Years51-55 Years56-60 Years61-65 Years66-70 Years71-75 Years76-80 Years>80 Years' or . = 'Select age5-17 Years18-24 Years25-35 Years36-40 Years41-45 Years46-50 Years51-55 Years56-60 Years61-65 Years66-70 Years71-75 Years76-80 Years>80 Years')]</value>
      <webElementGuid>6fcc3423-4f42-42e5-969b-ff3da2a44c02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
