<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Health Insurance Articles_media-object _deaa21</name>
   <tag></tag>
   <elementGuidId>f5fe115b-22be-4dfc-b0b5-4498705f0d4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='The Ultimate Guide to Organ Donation and Transplantation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.media-object.img-rounded.pull-left.mb-image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3630e42f-80a4-47db-87a8-cec0aab3fe3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>media-object img-rounded pull-left mb-image</value>
      <webElementGuid>2ed7bbab-8f4e-494e-90da-7f8db85db1df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>367</value>
      <webElementGuid>f079df6c-237a-4eb1-9f03-6af77fdd9f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>176</value>
      <webElementGuid>e6ca9f54-7b18-431d-9776-3c184d184a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>97dd9ac2-1cad-4cf2-b518-44428c76e3aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/../../upload_master/media/posts/July2023/organ-transplant.webp</value>
      <webElementGuid>9026ab55-ea77-4ce8-b5b1-9ffec9ef279c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>The Ultimate Guide to Organ Donation and Transplantation</value>
      <webElementGuid>dc4c12a5-cdf9-4678-8a7e-77dc9594027c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>The Ultimate Guide to Organ Donation and Transplantation</value>
      <webElementGuid>606315e3-9224-41c7-8d3d-b9edbe6c9925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;bg_color&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;blog_detail_body&quot;]/div[@class=&quot;blog_detail_body_left&quot;]/div[@class=&quot;media product_media_shadow&quot;]/div[@class=&quot;media_body_img&quot;]/a[@class=&quot;bloglst img_blog_list&quot;]/img[@class=&quot;media-object img-rounded pull-left mb-image&quot;]</value>
      <webElementGuid>41972bae-8067-45c5-81c7-2d5517426e4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='The Ultimate Guide to Organ Donation and Transplantation']</value>
      <webElementGuid>f7fec8f6-dc59-4625-81c4-929854c4e609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/a/img</value>
      <webElementGuid>11fb4c3a-3fc8-4a2a-8bc6-52258cbbaedc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/../../upload_master/media/posts/July2023/organ-transplant.webp' and @title = 'The Ultimate Guide to Organ Donation and Transplantation' and @alt = 'The Ultimate Guide to Organ Donation and Transplantation']</value>
      <webElementGuid>40038167-403d-4c8a-a216-b5e5f696e5a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
