<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Same as permanent address_cores_address</name>
   <tag></tag>
   <elementGuidId>ccac0899-d6f7-4e51-8b68-c9fc9982820a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cores_address_same_as</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cores_address_same_as']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41d64f92-89e8-4df6-8fd9-1a9d7f893399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>329e63f6-b9a2-4bea-bab0-10133a0e54fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cores_address</value>
      <webElementGuid>3ee5883e-1d12-4f15-80cc-d912beca416f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cores_address_same_as</value>
      <webElementGuid>8d9e4648-5735-466c-8b6e-b6fe19dc5151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cores_address</value>
      <webElementGuid>bc1ada08-e5ac-43c8-9395-bdd49e900421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>40ad4ea2-0a16-46ed-8f36-92a8dd7700dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cores_address_same_as&quot;)</value>
      <webElementGuid>c77a58fb-2cbc-4cfc-a3eb-d54d5941d5ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cores_address_same_as']</value>
      <webElementGuid>56fcc315-548c-4020-86bf-daf037300c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='proposer_details']/section/div/div/div[5]/div[2]/div/input</value>
      <webElementGuid>5fd2a7a1-54bb-46be-8b84-1770f2f7c722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>d6b3f591-342d-4343-9532-ff2b8a84e884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'cores_address' and @id = 'cores_address_same_as']</value>
      <webElementGuid>4ca5af9c-7cda-4885-9a73-831ea930eda0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
