<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_nominee_name</name>
   <tag></tag>
   <elementGuidId>cdda7df9-e7ff-419b-b51f-22315c239820</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nominee_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nominee_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7c4e04ac-4baf-4bca-8445-8581f2bbe5b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>bf9ed88f-999f-497a-80de-b38399aaada9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5893f127-c9b5-43f6-a275-ca39e718fa99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nominee_name</value>
      <webElementGuid>5cafb6bd-8e8d-4b43-a210-69f90de3e015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nominee_name</value>
      <webElementGuid>04d6d45e-5187-41e3-aeff-ede63258863e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>return validName(this);</value>
      <webElementGuid>0ff8fa71-2611-4be6-98eb-5fc491fbf3bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nominee Name</value>
      <webElementGuid>8384cbab-df5f-4c41-b5c3-65c4abc19ae7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input nominee_name</value>
      <webElementGuid>f7aac8fd-9dfd-40b6-8220-85be403a7d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nominee_name&quot;)</value>
      <webElementGuid>42fd7349-438d-4d49-8cf5-efe2eab31c28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nominee_name']</value>
      <webElementGuid>bc232eaa-16dc-4eee-94ff-5cfd7d85cf83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='proposer_details']/section/div/div/div[6]/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>570884b9-a7b5-4b86-bed5-a6d64e445494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>41e05640-5b1f-4055-b640-2d1e4238e92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nominee_name' and @id = 'nominee_name' and @placeholder = 'Nominee Name']</value>
      <webElementGuid>31764a61-12e1-4e3d-978b-771b87dc3642</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
