<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Weight_insured_members1weight</name>
   <tag></tag>
   <elementGuidId>96e65d9e-eb61-46c3-850f-f207d8639db3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#weight_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='weight_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a03e0e1b-4f45-40ff-a8e4-c9ce19da016a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4cd40e93-00ef-4a47-8b17-648920eb5901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>b9a87297-78ba-4f7e-9bd7-7f150702611f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>insured_members[1][weight]</value>
      <webElementGuid>f6c43e7f-ff63-4697-8d8d-44b246cbb273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>weight_1</value>
      <webElementGuid>925a9ab9-be40-4366-8d6a-3258a17f1fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>in kgs</value>
      <webElementGuid>f8c9d774-5a93-4343-9bcb-f4beb0dc360b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input insured_members insured_members_weight valid</value>
      <webElementGuid>26e0de28-670c-4973-8c90-67203da73da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>c3a4cff0-0b38-4655-a8db-711e6ea616e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>return isNumber(event, this, 3);</value>
      <webElementGuid>ea41e1a6-355b-4db1-a2f6-75259a60d07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;weight_1&quot;)</value>
      <webElementGuid>fe38d20b-c19c-4bc2-8346-08197bae507a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='weight_1']</value>
      <webElementGuid>6dde96a9-0248-469e-885b-4452a1341102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insured_details']/section/div/div/div/div/div/div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>220a0353-db61-46c1-8ada-437c5fb1a003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>3b6c0121-1f62-4f19-8af5-db83c0642c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'insured_members[1][weight]' and @id = 'weight_1' and @placeholder = 'in kgs']</value>
      <webElementGuid>3284becb-0e2b-4db0-a103-21f639ef3b2a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
