<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__insured_members1height_inches</name>
   <tag></tag>
   <elementGuidId>5ca7b19f-fb45-4363-9cec-3ef463d75b2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#height_inches_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='height_inches_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ffe1512-9898-4f61-beda-b8b628b63a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>8194d3ed-4468-47e6-8957-fd751201ad48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>c96468b8-d703-476f-b65b-784157ab605f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>insured_members[1][height_inches]</value>
      <webElementGuid>d279290f-0355-4084-8770-f0f1b39afb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>height_inches_1</value>
      <webElementGuid>cfdd64e6-90b5-498a-b1ad-8c69582af5f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Inches</value>
      <webElementGuid>36bfd436-b540-419a-81be-3e9fd829cde7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input insured_members insured_members_heightInches valid</value>
      <webElementGuid>3becd319-9d43-4aa7-9f54-7bcbf1fba27f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0e351477-cbbc-4ba8-9f4c-2a2ce7ed9654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>return isNumber(event,this,2);</value>
      <webElementGuid>7d2f1f6c-14af-4163-876e-dc0a40c5beae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;height_inches_1&quot;)</value>
      <webElementGuid>b6366bb5-9e92-4ac5-a49b-cadf80b00588</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='height_inches_1']</value>
      <webElementGuid>b3542306-7d99-426d-b232-af4a2187c87c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insured_details']/section/div/div/div/div/div/div[3]/div/div/div/div/div[3]/input</value>
      <webElementGuid>258e1528-b12c-45e9-8212-ff650add3d5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[3]/input</value>
      <webElementGuid>67a3562c-f76c-4321-861e-db119e620376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'insured_members[1][height_inches]' and @id = 'height_inches_1' and @placeholder = 'Inches']</value>
      <webElementGuid>7d268d56-1319-4b3a-9990-2ee06601d6db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
