<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Height_insured_members1height_feet</name>
   <tag></tag>
   <elementGuidId>937f48ce-9bea-4bf5-90b1-069023ce12b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#height_feet_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='height_feet_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>480eac7e-293a-41e7-a999-cd08086098d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>d502bf01-8962-479c-9d76-3bcb8ba0f428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>10588f78-e0ac-4f56-8c6b-802e8e7b520a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>insured_members[1][height_feet]</value>
      <webElementGuid>93fc5656-82ab-4150-9583-17c8b452d393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>height_feet_1</value>
      <webElementGuid>d767877e-a61a-4a75-84c9-697cced6fdc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Feet</value>
      <webElementGuid>f2411ad4-02ef-4d65-97b0-1de0ee321798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input insured_members text_right insured_members_heightFeet valid</value>
      <webElementGuid>ea8a1e13-d4e2-44f2-b3ba-387174d30829</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>66f2a47a-ded4-4e2e-ab61-a8433406c51f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>return isNumber(event,this,2);</value>
      <webElementGuid>e7b1d51b-a03c-4bd4-8b2e-c35d5ebf4957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;height_feet_1&quot;)</value>
      <webElementGuid>e8c6774f-25db-4e3f-b3ef-e1568c070a2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='height_feet_1']</value>
      <webElementGuid>4cb7f9f6-b960-4607-a496-99d8b6e2d9b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insured_details']/section/div/div/div/div/div/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>8dd4302b-a531-4f8c-b030-068af8aa5046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>1377dc7a-8b81-4000-9800-4a374db7c5d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'insured_members[1][height_feet]' and @id = 'height_feet_1' and @placeholder = 'Feet']</value>
      <webElementGuid>a0c2f6f8-c72e-4566-99b4-3e388c61194e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
