<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Emergency Contact No_EmergencyMobileNumber</name>
   <tag></tag>
   <elementGuidId>c01d5b0f-b7f6-4a9c-9ac9-3912de3558c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EmergencyMobileNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EmergencyMobileNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c8748b6-f0cd-42eb-9295-bd36735c6b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EmergencyMobileNumber</value>
      <webElementGuid>dc0a0614-3af8-424f-a71b-be9808d9379a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EmergencyMobileNumber</value>
      <webElementGuid>a69a0702-dab6-4f40-8174-d717dfc4155a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>6a219959-1d9f-45a1-9150-56e962360cf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>83ee6f59-d8e4-4ec7-9e86-2910a82fb3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input EmergencyMobileNumber</value>
      <webElementGuid>d404bf4d-2f94-42ff-861a-9a4e64055d3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter contact no</value>
      <webElementGuid>17c964b0-a7c3-4281-8318-365b02ffc067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>return isNumber(event, this, 10);</value>
      <webElementGuid>8db0ce11-f5cc-478d-a4a8-42869c0c8398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>c2e22008-493b-484d-a789-eb5590710dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EmergencyMobileNumber&quot;)</value>
      <webElementGuid>9b2e235e-9b64-4cbb-8738-6aba4f634dd4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EmergencyMobileNumber']</value>
      <webElementGuid>6dc94805-fcbc-402d-9971-e467c8df44ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='proposer_details']/section/div/div/div[3]/div[2]/div/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>cc3b18d3-0e2f-4f1f-b7e6-7c48b8a5368e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>ddc77d31-7e92-4584-9160-1fdebd1b3b66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'EmergencyMobileNumber' and @id = 'EmergencyMobileNumber' and @type = 'tel' and @placeholder = 'Enter contact no']</value>
      <webElementGuid>f7ec91bf-d623-4054-a421-836bae7abd54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
