<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Landmark_landmark</name>
   <tag></tag>
   <elementGuidId>98072dd8-08a8-48c8-98b1-d963cdd61f50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#landmark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='landmark']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec9c2ab5-f7b2-4ea8-b9ac-f41f5832e55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9bab3ca3-87f8-41f5-ab60-5ea2a4d98df4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>90d1396c-de9a-4916-adf4-dfee50417e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>landmark</value>
      <webElementGuid>b4bc5e42-1ce8-4c3f-9e50-d3d7989b6d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>landmark</value>
      <webElementGuid>1f2b8241-f9a6-4178-bc5b-50c169885a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type here</value>
      <webElementGuid>4b1c82dc-e3aa-423a-ad8a-db50b71fb7c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input landmark</value>
      <webElementGuid>382d8fc4-b7d6-433e-8d96-9f8c2497cae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>52741f30-fdc1-4a8b-86ec-1402ba78ce7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landmark&quot;)</value>
      <webElementGuid>3bc0866a-5a0f-45bd-83cd-4c09df64b1fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='landmark']</value>
      <webElementGuid>f6f89863-0001-4bd5-a689-c1493fa5c1d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='proposer_details']/section/div/div/div[4]/div[2]/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>1e271110-f720-45dd-b25d-1c97c7582332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>bc999b34-8cf6-4f43-a60d-89c0c33b8bdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'landmark' and @id = 'landmark' and @placeholder = 'Type here']</value>
      <webElementGuid>02d591d0-f4bd-4052-a304-f7d615086214</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
