<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_email_id</name>
   <tag></tag>
   <elementGuidId>e73080d7-93a4-4b5f-99f2-7576cd62af14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'email' and @name = 'email_id' and @id = 'email_id' and @placeholder = 'Enter Email ID']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#email_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@class='floating-input email_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fa911402-f119-4a95-af9f-16d3d45bf4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>5e5c9e16-dfb9-4c31-a096-321ec413ee78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>9d25619e-99d3-45ff-ba47-0858b1544845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email_id</value>
      <webElementGuid>bf1cecdc-7c58-4768-813e-9f6ddd45547b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email_id</value>
      <webElementGuid>6c13a0ab-8a33-4ed2-a170-d6b0608aba77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Email ID</value>
      <webElementGuid>da55087e-0ff7-4e87-b41b-9fa51b4abe5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input email_id</value>
      <webElementGuid>72676094-1811-4491-8317-b8ac1ced30ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email_id&quot;)</value>
      <webElementGuid>f20b0ad8-8229-4121-856f-41c9ee01cfa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email_id']</value>
      <webElementGuid>8ee8641a-1f82-4888-96a3-e67166b02144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='proposer_details']/section/div/div/div[3]/div[2]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>e4c6d9ad-55c6-437d-9d68-912cb252b7f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>3507d94a-00cd-4616-9e03-e023f496ab9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email_id' and @id = 'email_id' and @placeholder = 'Enter Email ID']</value>
      <webElementGuid>2993cbfb-f930-49a8-b029-844a4d7207c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
