<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nominee DOB_nomineeDob</name>
   <tag></tag>
   <elementGuidId>611ffdd6-ead3-404d-a582-410d65d8118b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nomineeDob</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nomineeDob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c6cbb90-564d-423a-aa25-5405e64f294f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>0748bd3a-5f00-494a-9e05-b25d71f76758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nomineeDob</value>
      <webElementGuid>44bf5bf6-6ed4-43ed-bb8b-7e6639dd9686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nomineeDob</value>
      <webElementGuid>095eb951-2164-48be-adfb-ee91ba34777e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD / MM / YYYY</value>
      <webElementGuid>095198d5-26bd-4dff-b528-c5588fca778e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input calendar_input_nominee calender_datepicker_input dob nomineeDob hasDatepicker</value>
      <webElementGuid>d665798c-6984-42da-9f60-d6b123570dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>c38f36bd-673d-4460-82fa-738dbf45389a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>427269a5-a9bd-416f-988a-1c659558d4b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>checkForNominee();</value>
      <webElementGuid>2025af3c-0246-451e-98ed-aca86c2936a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nomineeDob&quot;)</value>
      <webElementGuid>388e4dc8-aacf-4a03-a6af-5cf12425ec26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nomineeDob']</value>
      <webElementGuid>428d2839-0889-4a47-9fc9-b0288cb3186c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='proposer_details']/section/div/div/div[6]/div[2]/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>e0ae1b2d-316f-41f5-a33b-07f2d6780af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>6b03380a-7ec1-47da-8068-7adec845358b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'nomineeDob' and @id = 'nomineeDob' and @placeholder = 'DD / MM / YYYY']</value>
      <webElementGuid>7aa3629e-4c95-465c-8c21-db8a5661600e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
