<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Brother</name>
   <tag></tag>
   <elementGuidId>8788844d-f8a8-4296-9907-30178e8977da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='proposer_details']/section/div/div/div[6]/div[2]/div/div/div[2]/div/div/ul/li[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>0744267e-8721-490a-988b-6bc3f9069e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>drop_element</value>
      <webElementGuid>2a03da1a-6a98-40fa-9e65-fe280c9d557c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>BOTH</value>
      <webElementGuid>ef7a18e3-2a31-4a79-b1b8-7a3ba303bd44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Brother</value>
      <webElementGuid>bc91fde8-6352-4444-88be-7829c524c581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;proposer_details&quot;)/section[@class=&quot;form_sec&quot;]/div[@class=&quot;custom_container&quot;]/div[@class=&quot;custom_container_dropdown&quot;]/div[@class=&quot;form_card&quot;]/div[@class=&quot;nominee nominee_in&quot;]/div[@class=&quot;accordion_common_content&quot;]/div[@class=&quot;form_flex&quot;]/div[@class=&quot;column&quot;]/div[@class=&quot;common_input quoteflow_drpdown&quot;]/div[@class=&quot;form_input borderdinput drop_cont relation_input relation_input_width in&quot;]/ul[@class=&quot;custom_drop_cont&quot;]/li[@class=&quot;drop_element&quot;]</value>
      <webElementGuid>a1e6a666-b436-45c3-baeb-a6921af5b373</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='proposer_details']/section/div/div/div[6]/div[2]/div/div/div[2]/div/div/ul/li[5]</value>
      <webElementGuid>a96a4508-161b-4326-a79f-5ea1f269aff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mother'])[2]/following::li[1]</value>
      <webElementGuid>58080ce3-c77c-4730-9aca-e37d0dd680f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Father'])[2]/following::li[2]</value>
      <webElementGuid>c1e5ef64-6a4c-4812-a553-4a10ac6baee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sister'])[1]/preceding::li[1]</value>
      <webElementGuid>6cfed2eb-5fc4-40c0-8ef9-8482a58e3657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Son'])[2]/preceding::li[2]</value>
      <webElementGuid>5e3754e7-ea9b-4359-b0b2-6bea0ffc86b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Brother']/parent::*</value>
      <webElementGuid>5cdf0069-1275-485e-9e4a-95852d06e983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[5]</value>
      <webElementGuid>2976ff62-5271-40a3-a27c-a62a382353ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Brother' or . = 'Brother')]</value>
      <webElementGuid>f9887dac-5c9b-4e35-80fd-6c01db880de3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
