<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1</name>
   <tag></tag>
   <elementGuidId>8c1e23d9-9edc-47a4-bc52-8ad38f5f1f6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.proposaltermscondition > label.checkbox > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='health_questionnaire']/section/div[4]/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dc571c2b-2c4d-4d62-a34d-1786979fcf29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;health_questionnaire&quot;)/section[@class=&quot;form_sec new_questionnaire_styles&quot;]/div[@class=&quot;custom_container bg_ui&quot;]/div[@class=&quot;proposaltermscondition&quot;]/label[@class=&quot;checkbox&quot;]/span[1]</value>
      <webElementGuid>4cae6be6-e89e-4b75-b62e-45447cdd99f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='health_questionnaire']/section/div[4]/div/label/span</value>
      <webElementGuid>cf5e2b63-9dc2-4883-97bd-5f72626ccf80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/label/span</value>
      <webElementGuid>d3f8d1d7-0004-4601-915d-400a6b3b4fef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
