<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_for assistance with your existing policy_Close</name>
   <tag></tag>
   <elementGuidId>1f4c736b-0c80-4de8-ab34-ab806f073b8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='survey_popup']/div/div/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.Close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ba3aa0ef-9f6f-411e-a06d-d75c13cfb519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>e77af892-1d92-427d-98fd-402234ee5383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>8bd23eae-41ff-4777-bb73-288db93aeccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>19d4ec17-77e8-4324-8c7d-07192cc6703f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f378a44e-9f31-4030-ba76-6b0fdfb4528f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>8c5d2cba-dc66-4fbd-b49c-09adfd4d099e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>2c106c2e-fc7c-4a53-a613-51145ac26326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.careinsurance.com/cpproject/rhiclfrontend/assets/public/images/AB-Testing-Popup/cross-01.svg</value>
      <webElementGuid>81193419-f42f-4677-9479-6b0a8364d393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;survey_popup&quot;)/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ab2-modal-inner-content&quot;]/span[@class=&quot;close1 survey_close sec_popup exit_intent_close&quot;]/img[@class=&quot;Close&quot;]</value>
      <webElementGuid>20bc87f5-07af-422f-a7b9-c76234934e7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='survey_popup']/div/div/span/img</value>
      <webElementGuid>6324bb84-f118-458a-b355-413a1237b1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Close']</value>
      <webElementGuid>c2045b87-7fd1-4295-bbbf-d524524e9921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/span/img</value>
      <webElementGuid>a1018b56-6f6e-4634-8e25-2f5ae66f3b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Close' and @title = 'Close' and @src = 'https://www.careinsurance.com/cpproject/rhiclfrontend/assets/public/images/AB-Testing-Popup/cross-01.svg']</value>
      <webElementGuid>de9ef201-35e3-421e-9795-b0651744c15d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
