<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select age5-17 Years18-24 Years25-35_2c9cec</name>
   <tag></tag>
   <elementGuidId>9f4b6c51-1c49-42a5-b2f7-827fa1867a62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='ageGroupOfEldestMember']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;ageGroupOfEldestMember&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>734fc41a-f3d1-460f-81d0-355b539946e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>eldest_member lozad</value>
      <webElementGuid>e822bc12-0a25-437b-b8ab-d799085eead2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ageGroupOfEldestMember</value>
      <webElementGuid>a81dfabd-db74-49a8-bc06-909b3cad0e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-background-image</name>
      <type>Main</type>
      <value>https://www.careinsurance.com/rhicl/public/images/sem_dynamic/down-arrow.png</value>
      <webElementGuid>a73fd787-03f0-4b9a-a051-90bef48158d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3d5c461e-ddd1-455a-aa53-e543603e0bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>4c2f2937-385d-4b0c-a7d8-5800b200df75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select age5-17 Years18-24 Years25-35 Years36-40 Years41-45 Years46-50 Years51-55 Years56-60 Years61-65 Years66-70 Years71-75 Years76-80 Years>80 Years</value>
      <webElementGuid>23178888-e1ed-4874-9ba9-09fe84eec295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;care-quote-box&quot;)/div[@class=&quot;step2 Cr-PreQuote-InsuredDetails&quot;]/div[@class=&quot;form-group age_input&quot;]/select[@class=&quot;eldest_member lozad&quot;]</value>
      <webElementGuid>431248ab-2318-484e-8a4b-60fdceb021a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='ageGroupOfEldestMember']</value>
      <webElementGuid>3251b2d1-6abc-4c62-bc2b-7ee5cbb971f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='care-quote-box']/div[2]/div[3]/select</value>
      <webElementGuid>9be70bb1-69ea-48f3-87ce-a3f723c994ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mother'])[1]/following::select[1]</value>
      <webElementGuid>748e5f7e-ce03-4b0e-9459-f2a5de277160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Father'])[1]/following::select[1]</value>
      <webElementGuid>2c6c60af-f991-422c-b2f6-9ecd38d2db56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::select[1]</value>
      <webElementGuid>2e057b86-bd58-4f2f-a9da-40f5c371c6d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help us with your city'])[1]/preceding::select[1]</value>
      <webElementGuid>ccfdd8b2-cfeb-45e7-9477-9435bf670de1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/select</value>
      <webElementGuid>f55c8a42-4eef-4bad-8fc2-60a900fd955e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'ageGroupOfEldestMember' and (text() = 'Select age5-17 Years18-24 Years25-35 Years36-40 Years41-45 Years46-50 Years51-55 Years56-60 Years61-65 Years66-70 Years71-75 Years76-80 Years>80 Years' or . = 'Select age5-17 Years18-24 Years25-35 Years36-40 Years41-45 Years46-50 Years51-55 Years56-60 Years61-65 Years66-70 Years71-75 Years76-80 Years>80 Years')]</value>
      <webElementGuid>4f7b1de7-9e49-430e-9315-4e07000e37b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
