<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Download__9vx6</name>
   <tag></tag>
   <elementGuidId>866546d7-2202-433e-90c0-b3462f232ca8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main_block']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img._9vx6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>473b7275-2085-402c-91f3-d131db6aa520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pps.whatsapp.net/v/t61.24694-24/344378065_924646018864276_7841680111878976473_n.jpg?ccb=11-4&amp;oh=01_AdQRfRNoV_TOFz8UmwAifYq9YsliuZnvOaxGkyTptUJz3w&amp;oe=64AA32E1</value>
      <webElementGuid>c446b92d-d396-44c6-8ece-26191102a3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Profile Picture</value>
      <webElementGuid>abde9c20-2055-479a-98ad-0eaab9cf1e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_9vx6</value>
      <webElementGuid>3257f87e-8117-4cc2-a5ad-190d988febca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_block&quot;)/div[@class=&quot;_9vd6 _9t33 _9bir _9bj3 _9bhj _9v12 _9tau _9tay _9u6w _9se- _9u5y&quot;]/img[@class=&quot;_9vx6&quot;]</value>
      <webElementGuid>a4787854-fbc7-4164-85ea-ff52fbe218a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main_block']/div/img</value>
      <webElementGuid>a80d18b7-371f-4329-bc5e-0d88bafd42e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Profile Picture']</value>
      <webElementGuid>63f34cf0-2413-4acb-9ada-4d614f88d6a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>66dcce95-a499-4ae7-863b-8bb32677bb05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pps.whatsapp.net/v/t61.24694-24/344378065_924646018864276_7841680111878976473_n.jpg?ccb=11-4&amp;oh=01_AdQRfRNoV_TOFz8UmwAifYq9YsliuZnvOaxGkyTptUJz3w&amp;oe=64AA32E1' and @alt = 'Profile Picture']</value>
      <webElementGuid>576150e6-64c9-48af-b040-7f0003d88678</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
