<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Claim Support_mobile_no</name>
   <tag></tag>
   <elementGuidId>05ab65ed-22f5-4b5d-8924-6f419e21c801</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#mobile_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='mobile_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1def49d-9cf9-4150-9846-6785fec49c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>d9287e63-2d8e-4557-bef3-e190d538ea29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input valid</value>
      <webElementGuid>1b598073-f371-4423-8179-0716d64440bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mobile_no</value>
      <webElementGuid>ed56a4fa-edfa-4110-b708-f6a2a1153186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>mobile_no</value>
      <webElementGuid>ef6d643d-93f3-400a-b80f-0f810a7b7ab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>da17f14e-f071-4643-af06-a994c387258f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>bfa38a2d-1bfb-47f4-ae76-cabaefcc88f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>return isNumber(event, this, 10);</value>
      <webElementGuid>70c69b8b-509a-4edd-8225-76552a8bba7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobile_no&quot;)</value>
      <webElementGuid>dd6798f9-feb5-41c7-9671-b49d2f1d78a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='mobile_no']</value>
      <webElementGuid>58e32dbf-a328-481b-8ce6-ed0b05c64edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='quote-form-step-1']/div/div/input</value>
      <webElementGuid>4e7e7fed-e35e-4c2e-969f-3503f949eafc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/form/div/div/input</value>
      <webElementGuid>d22f2460-7fcc-4348-84bf-53cfc5aac1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'mobile_no' and @id = 'mobile_no' and @type = 'tel']</value>
      <webElementGuid>3ed0d00b-0d7f-4018-b80a-d2d52e34b5aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
