<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Live Chat_Close</name>
   <tag></tag>
   <elementGuidId>fb98a846-9862-4d51-89d5-5c1668c48edf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='survey_popup']/div/div/span/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.Close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e0ac0ab8-c795-48d3-8c67-7c60126d27ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>1e46f1d0-8223-4c3e-9359-ca89c81d0c6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>d18d11ca-6cab-44a1-ac0e-310f7c013be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Close</value>
      <webElementGuid>37b2ab38-0408-494b-9690-4470e85c56e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>8cc6b587-fde2-453b-b716-59e22ae007df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>1b0383fb-7a94-4927-8060-b198c50ea270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>0ed76f50-bf79-4f60-b2d2-bfb871e79f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.careinsurance.com/cpproject/rhiclfrontend/assets/public/images/AB-Testing-Popup/cross-01.svg</value>
      <webElementGuid>176b0843-f46c-488a-8261-8f44964b6c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;survey_popup&quot;)/div[@class=&quot;modal-content&quot;]/div[@class=&quot;ab2-modal-inner-content&quot;]/span[@class=&quot;close1 survey_close sec_popup exit_intent_close&quot;]/img[@class=&quot;Close&quot;]</value>
      <webElementGuid>c1563149-8ec6-4cc7-a45b-111f07d5dd6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='survey_popup']/div/div/span/img</value>
      <webElementGuid>52fe2f34-7ce3-4f54-baba-5653c7413117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Close']</value>
      <webElementGuid>b851eba9-a888-4667-b4f3-55a23a6ed75b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/img</value>
      <webElementGuid>c6c85532-673b-4b7a-b48a-df99f4ebe32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Close' and @title = 'Close' and @src = 'https://www.careinsurance.com/cpproject/rhiclfrontend/assets/public/images/AB-Testing-Popup/cross-01.svg']</value>
      <webElementGuid>67d6360c-e7cf-4c9c-b431-e521df676386</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
