<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Continue with detailed form to pay</name>
   <tag></tag>
   <elementGuidId>55de8c80-1c01-49f1-a8c7-84befaeaaddb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.link_brown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='standardPaymentFlow();']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1104fa4c-e4c2-41a9-9c92-5a8b57c41174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>7ed0bdcf-3d94-4f4d-b822-01f8a38de4d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>standardPaymentFlow();</value>
      <webElementGuid>b7431cc7-fe5b-4dc8-a996-a380cc2d8861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link_brown</value>
      <webElementGuid>ab058a49-49c8-44af-8c94-0a0fce9533c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue with detailed form to pay</value>
      <webElementGuid>d170752a-ba9a-4d67-98c7-aa14c52b63d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quick-proposer-form&quot;)/div[@class=&quot;custom_container&quot;]/div[@class=&quot;center_checkbox&quot;]/div[@class=&quot;popup_btn_group&quot;]/div[@class=&quot;text-center&quot;]/a[@class=&quot;link_brown&quot;]</value>
      <webElementGuid>3dfaa2f5-318c-4c8b-a2f7-4758654898d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='standardPaymentFlow();']</value>
      <webElementGuid>cc05ec4b-1189-42a9-8ff4-a69eb76b9c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='quick-proposer-form']/div/div[2]/div/div/a</value>
      <webElementGuid>664ac3af-7d72-4410-a986-9a479548e7a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Continue with detailed form to pay')]</value>
      <webElementGuid>cd96f842-a54e-4cf1-8b0c-ba4e4c5fafa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::a[1]</value>
      <webElementGuid>367a796d-d592-40b0-bc66-2b71ac16a6a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='back'])[1]/following::a[1]</value>
      <webElementGuid>c5180109-12f2-44d9-a69d-27c2128505a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[6]/preceding::a[1]</value>
      <webElementGuid>0563c6bb-969e-4ecd-ac98-8f781dfe850b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Proposal Summary'])[1]/preceding::a[1]</value>
      <webElementGuid>77ccc257-7a96-48df-b24d-f4fd9199b597</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue with detailed form to pay']/parent::*</value>
      <webElementGuid>9a8ad727-b284-4632-8438-b2a18f74b237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[8]</value>
      <webElementGuid>94b4a84d-ca57-4fd1-be5d-93a9c8db1750</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>835ed261-0e0b-48e6-9d51-2cbfb2ed6da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = 'Continue with detailed form to pay' or . = 'Continue with detailed form to pay')]</value>
      <webElementGuid>68fb5122-9014-4217-bea3-2a103461995b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
