<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DATE OF BIRTH_aadhar_dob</name>
   <tag></tag>
   <elementGuidId>867efe90-4863-4eb4-b433-04184613170d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aadhar_dob</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='aadhar_dob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61e77774-a010-41eb-8d96-18c8a7e3f1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>2644069f-0fa2-425c-8baf-d9fc395e3c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2b3d1436-1ef0-4a0b-a638-81c28577cf65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aadhar_dob</value>
      <webElementGuid>0c23bd81-21e2-4233-be77-a337249e00d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>aadhar_dob</value>
      <webElementGuid>b05af228-8f2d-475c-8b5a-c3d44d88f246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>10455c8d-b847-492a-841f-3cd8f591ba2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD / MM / YYYY</value>
      <webElementGuid>c440f2da-7a13-4898-b172-9e3ac31368fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input aadhar_dob</value>
      <webElementGuid>b8ae7306-04fe-46ff-a153-26298477b7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kyc_container&quot;)/div[@class=&quot;kyc_details_cont adhar_card_details&quot;]/div[@class=&quot;kyc_details_wrapper&quot;]/div[@class=&quot;form_flex&quot;]/div[@class=&quot;column&quot;]/div[@class=&quot;common_input&quot;]/div[@class=&quot;form_input borderdinput&quot;]/div[@class=&quot;floating-label&quot;]/input[@id=&quot;aadhar_dob&quot;]</value>
      <webElementGuid>cdd7141f-1d3f-4e36-9284-9a41c30c38d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='aadhar_dob']</value>
      <webElementGuid>a418fd84-1c52-44e4-b053-61da8df2051b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kyc_container']/div[3]/div/div/div[4]/div/div/div/input</value>
      <webElementGuid>3280334e-96e1-4289-922a-e43e1c9a1db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[4]/div/div/div/input</value>
      <webElementGuid>3f655e0e-5c13-4e02-9dc2-ac72f431e9d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'aadhar_dob' and @name = 'aadhar_dob' and @placeholder = 'DD / MM / YYYY']</value>
      <webElementGuid>ed9dcb01-8078-41f7-ba9a-fdf0a49ab499</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
