<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Aadhaar ( Last 4 digits of Aadhaar )_r_8eb722</name>
   <tag></tag>
   <elementGuidId>d42d187d-021c-4c4e-b674-e73bb86b121d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.kyc_item.ekyc_adhar_card > span.radio_checkmark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kyc_container']/div/label[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b7f4f671-2f2c-442d-84d3-6637a8460412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio_checkmark</value>
      <webElementGuid>fc803d5f-1469-42ff-a3d1-63df4e4a093b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kyc_container&quot;)/div[@class=&quot;kyc_options&quot;]/label[@class=&quot;kyc_item ekyc_adhar_card&quot;]/span[@class=&quot;radio_checkmark&quot;]</value>
      <webElementGuid>246604eb-c9b4-4ce5-804e-349b6a8969f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kyc_container']/div/label[2]/span</value>
      <webElementGuid>373c400c-ce95-4984-aed2-7ed48beadf80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label[2]/span</value>
      <webElementGuid>583aea02-ae3e-46a6-8471-e9266d6c4704</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
