<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Download cashless card</name>
   <tag></tag>
   <elementGuidId>7d9e9b2f-4bb0-4af5-a967-0b23fef5c10b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ember51</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ember51']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7bca4ded-6853-4ac4-8b3a-631c9155f32a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ember51</value>
      <webElementGuid>78d30eb7-8cf2-4be5-abc3-e6e669ba820d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-img-button ember-view</value>
      <webElementGuid>3d94df08-f9c0-46bd-aab0-9be6961c71af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
  Download cashless card
</value>
      <webElementGuid>7ccc15bb-8d56-4a5a-ba1f-2f049e5ea47e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember51&quot;)</value>
      <webElementGuid>c5940431-c87d-43d5-a859-11639de9cb86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Contact Us/Page_How we can help you  WhatsApp Chat Sup_45a006/iframe_Welcome. How may I help you today_fc_widget</value>
      <webElementGuid>ad6295d7-0413-4ab2-9f61-8e6464d4606e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ember51']</value>
      <webElementGuid>96106859-5789-41c2-90da-fb16a3a90c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ember32']/div/button</value>
      <webElementGuid>0a111f2c-b1fe-49b6-8044-9a1139de903d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CARE Web Bot'])[2]/following::button[1]</value>
      <webElementGuid>8b492972-4a7e-4b4c-b901-5e9eb8aea0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Messages'])[1]/following::button[1]</value>
      <webElementGuid>7aef109c-fc29-4f54-bd02-065d39ceb1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>1a726823-8de3-41f0-99d2-82eaab3212c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ember51' and (text() = '
  Download cashless card
' or . = '
  Download cashless card
')]</value>
      <webElementGuid>4a5b2a01-d41c-4363-a987-3200faa2d749</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
