<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CARE Insurance Live chat_d_hotline minimize</name>
   <tag></tag>
   <elementGuidId>72140c65-e977-4301-9447-f7effc447924</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ember3']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3a012893-2dd2-433a-9b4c-b3a36d7b14a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d_hotline minimize  </value>
      <webElementGuid>82dac4c9-e0bc-440f-a965-91038e71c2aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>868f7f0e-e54a-4623-822f-a5af9b78f826</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bf5c0c6c-af9f-4c09-b64a-5a8abb98cbd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Close widget</value>
      <webElementGuid>f7db810c-d0c7-41fd-97c5-c7f530babe88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ember-action-21</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>895f8401-3de8-4336-af2a-b5af88d4d1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ember3&quot;)/div[@class=&quot;d_hotline minimize&quot;]</value>
      <webElementGuid>96e3d78f-9d2d-481c-9c6e-9008b899ecc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Contact Us/Page_How we can help you  WhatsApp Chat Sup_45a006/iframe_Welcome. How may I help you today_fc_widget</value>
      <webElementGuid>22b98fc2-4662-41a4-8b3f-3ccedc017e84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ember3']/div</value>
      <webElementGuid>7f399831-247a-4b24-b5e6-1e5355b6c3df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div</value>
      <webElementGuid>244b4135-af45-4a88-ac04-c8d36c166083</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
