<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Welcome. How may I help you today_fc_widget</name>
   <tag></tag>
   <elementGuidId>576e597d-4042-4322-9842-a31ca9d48210</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fc_widget</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='fc_widget']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9dbd3a05-0502-4e73-a799-83eff9d5c7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fc_widget</value>
      <webElementGuid>8dafaf9b-8b2e-4a5b-805d-d52e2dacf01a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fc_widget</value>
      <webElementGuid>b2420305-a093-4a7e-9b06-12f9c714f999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Chat</value>
      <webElementGuid>ace95dfa-107f-4749-83d7-0988c0a4d352</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3dc067ef-8c1f-4fdf-b6da-35506d8a5886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>516ca9fa-fc2b-4ec5-82f7-5bb6d2e2b1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>webkitallowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2d47ac61-eb25-49a3-9a0c-1abe3a6630a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mozallowfullscreen</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bb2433e6-822f-4ca0-bba4-5ee0de8d58dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fc_widget&quot;)</value>
      <webElementGuid>f5d64b71-7933-47e2-b4ba-d914cda25596</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='fc_widget']</value>
      <webElementGuid>cefa7d9f-82fd-46fe-be6f-a63608b9d3ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fc_frame']/iframe</value>
      <webElementGuid>163f0b69-af1e-4a24-82b0-f8c1123362b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/iframe</value>
      <webElementGuid>66ec171e-68ce-4fc7-9e87-59fa9dbcbf98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'fc_widget' and @name = 'fc_widget' and @title = 'Chat']</value>
      <webElementGuid>88ce4f76-d68d-41c0-a47d-78158cc3a385</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
