<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Download the Care Health Insurance - Cu_d02ecd</name>
   <tag></tag>
   <elementGuidId>50656dad-0341-4086-bb19-6d76fa6017e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.app_iocn > img.lozad</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='app_download']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>984b2051-e8db-4ee7-bab5-e53866916141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>254</value>
      <webElementGuid>2870fc68-7ff3-4133-b86c-7a80d6f14223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>9c70987e-c7d4-43fe-9bd5-202df96f45fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lozad</value>
      <webElementGuid>e0fb6550-75e2-440a-977e-2717aa5f5f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>app_download</value>
      <webElementGuid>60eef8ac-948d-4c2b-9961-5901ba4f3e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>app_download</value>
      <webElementGuid>dab772e0-9298-4237-8ab7-d2c5c8ee4733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.careinsurance.com/assets/images/shpimg/Mobile_App.png</value>
      <webElementGuid>fe9890a7-a9c0-4f92-ae3f-234460357298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.careinsurance.com/assets/images/shpimg/Mobile_App.png</value>
      <webElementGuid>b2289789-df25-49cb-b84c-0fb2b53c0263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>50e16e28-88a9-4868-ba49-9d05b01ad0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cards_show Chrome_view&quot;]/section[@class=&quot;support_cont&quot;]/div[@class=&quot;custom_container&quot;]/div[@class=&quot;support_details_section&quot;]/div[@class=&quot;support_method&quot;]/div[@class=&quot;step_container&quot;]/div[@class=&quot;help_details flex_div&quot;]/div[@class=&quot;app_download&quot;]/div[@class=&quot;ios_android_icon&quot;]/p[@class=&quot;app_iocn&quot;]/img[@class=&quot;lozad&quot;]</value>
      <webElementGuid>bbd5420a-7053-457a-b3cc-f19cba70a18d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='app_download']</value>
      <webElementGuid>2803f7f7-0902-4380-8f9e-a8860b7a9e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/img</value>
      <webElementGuid>80bd47bc-a976-4185-9ed8-334994c154b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'app_download' and @title = 'app_download' and @src = 'https://www.careinsurance.com/assets/images/shpimg/Mobile_App.png']</value>
      <webElementGuid>21b83ed9-9bdc-4086-86be-b4e512758c8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
