<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__sendLinkMob</name>
   <tag></tag>
   <elementGuidId>3f5ba5d0-c7ff-4002-a1a4-1a2a8dff33af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;sendLinkMob&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='sendLinkMob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3acbb4b7-b98b-4658-aad1-0e91028da6b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input</value>
      <webElementGuid>3da8c730-2c02-4c8b-ab75-41691b230bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>920e91b6-ce33-47cd-93ed-63c069134caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>3d8151d8-d5db-4f8c-af97-55eab5a2818c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>sendLinkMob</value>
      <webElementGuid>b2951759-df16-4bce-b473-e9adfcfea7a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Phone Number</value>
      <webElementGuid>2436db2d-6a3a-4ad1-bbbe-d2ba08af10b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f8a6c769-35f7-4bdb-a96b-dfe32e1bc7e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>return isNumber(event, this, 10);</value>
      <webElementGuid>ca5ed5cf-0d86-43de-b618-27756c612e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cards_show Chrome_view&quot;]/div[@class=&quot;get_app_link_popup popup_one&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-inner-content&quot;]/div[@class=&quot;generaltxt_container_about1&quot;]/div[@class=&quot;get_app_link_cont desktop_poup&quot;]/form[1]/div[@class=&quot;common_input&quot;]/div[@class=&quot;form_input borderdinput&quot;]/div[@class=&quot;floating-label&quot;]/input[@class=&quot;floating-input&quot;]</value>
      <webElementGuid>852a5eee-1f41-421e-975d-2e3c953daf01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='sendLinkMob']</value>
      <webElementGuid>ae1d7042-9711-4c01-90ef-915302cc571d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/form/div/div/div/input</value>
      <webElementGuid>e84e8025-ccac-4d82-af09-6b534b8563bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'sendLinkMob' and @placeholder = 'Phone Number']</value>
      <webElementGuid>bc6cee39-7509-4acb-a566-67cddc740e62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
