<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>acea6bdf-e3e4-45d6-abc0-6813555b6b8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.close1.comon_close_btn.link_pop_close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[2]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>55aad4e7-ff46-41fb-9187-be111027fc61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close1 comon_close_btn link_pop_close</value>
      <webElementGuid>5615a3c5-5053-4783-8998-d91fa1bb5e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>e62cc484-8c59-4b36-b488-aff16e7db14d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cards_show Chrome_view&quot;]/div[@class=&quot;get_app_link_popup popup_one&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-inner-content&quot;]/span[@class=&quot;close1 comon_close_btn link_pop_close&quot;]</value>
      <webElementGuid>9cd02695-0cfc-4f04-8468-1c1d4a3c5a7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[2]/following::span[1]</value>
      <webElementGuid>eb70db71-0fdb-4fa0-ae28-ad928fde2ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::span[3]</value>
      <webElementGuid>c58557ef-70b1-4d49-a4ea-6d0e704a5e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[2]/preceding::span[1]</value>
      <webElementGuid>71bd5ca5-1472-48ac-8c45-3e7447dd5bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Just select the digital platform of your choice &amp; we are there to serve you.'])[1]/preceding::span[1]</value>
      <webElementGuid>6325a585-3ded-463b-a259-0e40232f1d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/span</value>
      <webElementGuid>bdd80ffa-e9b6-493f-81d1-1a55e8310e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>46d13cc4-4bb2-4798-a820-5f067c8f859b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
