<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_8860402452</name>
   <tag></tag>
   <elementGuidId>77f716c3-a346-4857-bfd7-6adde48258f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.step_container > a.help_details.flex_div.align_item > div > span.contact_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect with us on Whatsapp'])[1]/following::span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>83ac7836-9be2-4a53-a4a2-ce40b8464689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>contact_no</value>
      <webElementGuid>efa945e3-716d-4568-855e-4fdadd601b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>8860402452</value>
      <webElementGuid>065fab20-5ac4-4787-be5e-169d4c984759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cards_show Chrome_view&quot;]/section[@class=&quot;support_cont&quot;]/div[@class=&quot;custom_container&quot;]/div[@class=&quot;support_details_section&quot;]/div[@class=&quot;support_method&quot;]/div[@class=&quot;step_container&quot;]/a[@class=&quot;help_details flex_div align_item&quot;]/div[1]/span[@class=&quot;contact_no&quot;]</value>
      <webElementGuid>23b41446-65fe-4aa0-9775-97add6cdaeda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect with us on Whatsapp'])[1]/following::span[1]</value>
      <webElementGuid>6287a42f-0540-4054-a71e-9f4dd87d30a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Or'])[2]/following::span[2]</value>
      <webElementGuid>ab129e54-1e8d-4379-8034-96feb58de8e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect with us on Chatbot'])[1]/preceding::span[2]</value>
      <webElementGuid>90083149-ec92-4cae-bfc4-2d5b41c2aab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here'])[1]/preceding::span[2]</value>
      <webElementGuid>08d25d37-f8aa-4d29-9ace-204b64f297c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/div/span</value>
      <webElementGuid>a102debb-1df2-4de6-9688-37ef1305c7e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '8860402452' or . = '8860402452')]</value>
      <webElementGuid>d050b746-9206-45a3-b643-654ba97f8599</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
