<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pay                                 _48de31</name>
   <tag></tag>
   <elementGuidId>ce6d49d4-4aa5-4bed-a59c-51cb9db5f0e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#common_pay_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='common_pay_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f7a7e0a8-859c-4cdb-aac9-4ea674b55117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>01274497-3688-44f9-a801-91c763e1b9ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>30c18c0a-7fa8-4a1a-a670-8424e881634c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>common_pay_btn</value>
      <webElementGuid>59cc400a-aab5-4094-be6d-787645da3727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>dataToAdobeOnMakePayment();</value>
      <webElementGuid>70cd5565-a2bd-49f9-b7de-10fe8420c6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pay 
                      
                        15716
                    
                </value>
      <webElementGuid>89eb85d6-d1f5-4f7a-a9d0-854c355a11b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;credit_card_form&quot;)/div[@class=&quot;payment_form_btn&quot;]/button[@id=&quot;common_pay_btn&quot;]</value>
      <webElementGuid>e02b05a2-6dd9-49d0-aabf-6a7c6de6e2cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='common_pay_btn']</value>
      <webElementGuid>44df648d-a857-450b-8e9e-5580a49a5d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='credit_card_form']/div[2]/button</value>
      <webElementGuid>666f83a6-cc49-42ab-90b2-d335a1bb8b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Securely save this card for a faster checkout next time'])[1]/following::button[1]</value>
      <webElementGuid>0bc2b918-972b-4b27-8fd3-c465eb4c8f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Last 3 Digits printed on the back of the card'])[1]/following::button[1]</value>
      <webElementGuid>b316bc94-84ec-44b8-9d6a-f7821368cdc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter Your Card Details'])[2]/preceding::button[1]</value>
      <webElementGuid>c0954b6e-c42f-490f-ba31-9684a292d96b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Card Number'])[2]/preceding::button[1]</value>
      <webElementGuid>7a9cb621-7368-45b5-aa1b-e07b3be4995f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pay']/parent::*</value>
      <webElementGuid>1e1db2cd-dc54-435d-963c-244d61270289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>623c638c-2155-47f7-9c4e-5c80f7886048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'common_pay_btn' and (text() = 'Pay 
                      
                        15716
                    
                ' or . = 'Pay 
                      
                        15716
                    
                ')]</value>
      <webElementGuid>dd43da0c-b597-444d-be4d-7d8151caf834</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
