<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Card Number_card_number_iframe_PD7ZL_30eb09</name>
   <tag></tag>
   <elementGuidId>fcc563de-ae53-4668-b15e-875222011b68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;card_number_iframe_PD7ZLGnpzwcT5Lsm&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='card_number_iframe_PD7ZLGnpzwcT5Lsm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>96782137-7dd9-433b-92d3-de22ba1f5d75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://api.juspay.in/iframe-element?detected_origin=www.careinsurance.com&amp;version=3.1</value>
      <webElementGuid>a22d33dc-a5d7-40b2-b73b-d852546383b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>00caa4bd-e607-47d4-865b-cec8760a1b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d5b4dd2f-d108-4f29-bfed-4d8bb6b2a7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>05b75928-017c-47e5-bff1-b38e6c4a4d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card_number_iframe_PD7ZLGnpzwcT5Lsm</value>
      <webElementGuid>2a481e44-e07a-4470-a5d8-79847e65517f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card_number_iframe</value>
      <webElementGuid>d7e0a75d-435b-4c78-8558-3928e01e51ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;credit_card_form&quot;)/div[@class=&quot;payment_input_box&quot;]/div[@class=&quot;content_padding&quot;]/div[@class=&quot;form-horizontal offset4 span4&quot;]/div[@class=&quot;card_number_div&quot;]/iframe[@class=&quot;card_number_iframe&quot;]</value>
      <webElementGuid>0ec18f6f-1e63-4ec6-868e-2703f9fbcb94</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='card_number_iframe_PD7ZLGnpzwcT5Lsm']</value>
      <webElementGuid>f1dc928a-6900-4ae7-a73a-2d1b10316bc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='credit_card_form']/div/div/div[2]/div/iframe</value>
      <webElementGuid>1f4fb0b9-5130-4794-8c4d-8708b031e85c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>0405fd8d-32eb-4fab-a23c-263ad90e5ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://api.juspay.in/iframe-element?detected_origin=www.careinsurance.com&amp;version=3.1' and @name = 'card_number_iframe_PD7ZLGnpzwcT5Lsm']</value>
      <webElementGuid>7a071f1d-e5f4-44f4-98f5-cce9a38ce962</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
