<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(id(, , card_number, , ))_card_number</name>
   <tag></tag>
   <elementGuidId>311c6ff1-514c-4e52-be2e-cb709b5fb18b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#card_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='card_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c77ffb2-8c22-4c1a-a128-bec684a6d7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>0eabdc80-bb13-4017-9a33-4ce1290cbc97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>xxxx-xxxx-xxxx-xxxx</value>
      <webElementGuid>368f0a4d-3bb9-48e1-877c-7240c722eb0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>card_number</value>
      <webElementGuid>b5c1b4b5-c13f-4aba-b012-45ec21a555e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>card_number</value>
      <webElementGuid>449345ff-d5bc-40ea-bb4b-9a9c217d1729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card_number</value>
      <webElementGuid>7822ef23-0858-4f9a-81ea-86c8f7cbfedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6e3fcaef-b9f0-46f5-8aab-4251d066e8c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-form_id</name>
      <type>Main</type>
      <value>#credit_card_form</value>
      <webElementGuid>af775589-3009-48ea-9791-cf7b1cadcacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return isOnlyNumeric(event);</value>
      <webElementGuid>232abdca-f54b-439f-aa32-6535b0cdc99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>97d76158-fc58-48f7-ab86-80e2f413a9a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-merchant_id</name>
      <type>Main</type>
      <value>religare</value>
      <webElementGuid>6f22edbe-3295-4cba-82c2-1b60bdab7d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;card_number&quot;)</value>
      <webElementGuid>b91b5f9f-f1ba-4350-a98e-d06b50d4ff5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Complete Form/Page_Care Payment/iframe_Card Number_card_number_iframe_PD7ZL_30eb09</value>
      <webElementGuid>68beca4d-834d-4187-9788-d2b9d5af69a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='card_number']</value>
      <webElementGuid>4ced763d-046f-4bbc-b36f-ae260b18fad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>296bece4-30ec-4777-a9c6-7a3dc8accbe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @placeholder = 'xxxx-xxxx-xxxx-xxxx' and @name = 'card_number' and @id = 'card_number']</value>
      <webElementGuid>729c41db-2793-49c3-b350-8ee71deb2449</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
