<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Continue to Chat</name>
   <tag></tag>
   <elementGuidId>7847e8cb-5e57-4f32-96f7-2e73a5a9d0b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#action-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='action-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>df5f8f3b-756f-4dc7-adc3-ed6a363593eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://web.whatsapp.com/send/?phone=918860402452&amp;text=hi</value>
      <webElementGuid>c5f7765d-7b66-435c-b23c-1fe22d629dfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Share on WhatsApp</value>
      <webElementGuid>b1370b95-b0dd-47c5-a942-b86da8182b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>action-button</value>
      <webElementGuid>79691ce7-2dad-4990-a2dd-6b31bb2f140c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_9vcv _advm _9scb</value>
      <webElementGuid>0a6a6b80-7d5a-41f4-911c-3d84eececf78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ms</name>
      <type>Main</type>
      <value>{&quot;creative&quot;:&quot;link&quot;}</value>
      <webElementGuid>6b7f1caa-c18c-4aa8-bb7a-6ee49ad24468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue to Chat</value>
      <webElementGuid>a7d6c26e-df66-48d1-b737-8f067162eb10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;action-button&quot;)</value>
      <webElementGuid>b0eb5db8-2bb5-4ca2-9c7b-0912fe993897</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='action-button']</value>
      <webElementGuid>d0dd0e89-11ce-465c-a7e9-a71411912e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main_block']/div/a</value>
      <webElementGuid>dedba34a-222f-4199-9ec4-477658eea76b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Care Health Insurance'])[1]/following::a[1]</value>
      <webElementGuid>cf74afd8-6085-4aaf-a018-a865b2821cc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[2]/following::a[2]</value>
      <webElementGuid>a76e85b0-41cd-4ba5-a3b1-384998caa237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Don', &quot;'&quot;, 't have WhatsApp yet?')])[1]/preceding::a[1]</value>
      <webElementGuid>88a28a45-ff43-4801-a8a6-db649178e36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://web.whatsapp.com/send/?phone=918860402452&amp;text=hi')]</value>
      <webElementGuid>160f5214-33ba-441a-bf68-74160f0fba2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/a</value>
      <webElementGuid>2caec955-e485-4b05-aed3-f3f4837947ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://web.whatsapp.com/send/?phone=918860402452&amp;text=hi' and @title = 'Share on WhatsApp' and @id = 'action-button' and (text() = 'Continue to Chat' or . = 'Continue to Chat')]</value>
      <webElementGuid>110b1feb-7474-4177-b9d9-b3ef7a18ce22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
