<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Continue to Chat</name>
   <tag></tag>
   <elementGuidId>b91b8f49-e4cc-4ab3-bcec-ebc6478818d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='action-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#action-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>70d4f952-e5e8-4a1d-ac73-d8069280ab72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://web.whatsapp.com/send/?phone=918860402452&amp;text=hi</value>
      <webElementGuid>3999dffe-aa01-4119-a8fc-bf459e4ac37d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Share on WhatsApp</value>
      <webElementGuid>4c3749d5-52c1-4e07-8c9a-c2e931183193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>action-button</value>
      <webElementGuid>34694219-35df-4d9f-b3c4-cb3b08197292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_9vcv _advm _9scb</value>
      <webElementGuid>c0feec51-bff8-4778-82e6-d0b87a89be65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ms</name>
      <type>Main</type>
      <value>{&quot;creative&quot;:&quot;link&quot;}</value>
      <webElementGuid>44ac9ae8-6dfe-4b67-8c82-c27a64aa949c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue to Chat</value>
      <webElementGuid>dbd011fb-ea38-46d0-919d-23dbfc469013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;action-button&quot;)</value>
      <webElementGuid>5ca256ad-13b2-42b5-9301-62dd06536f04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='action-button']</value>
      <webElementGuid>6b4c2f39-31c4-488b-93bf-a7a8f7002959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main_block']/div/a</value>
      <webElementGuid>8253884d-a448-482f-8e9f-f73f4481039e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Care Health Insurance'])[1]/following::a[1]</value>
      <webElementGuid>d163e675-4e37-4645-88d5-97a28a207f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download'])[2]/following::a[2]</value>
      <webElementGuid>bad1b5dd-cdb4-4254-b864-9b88c35b31ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Don', &quot;'&quot;, 't have WhatsApp yet?')])[1]/preceding::a[1]</value>
      <webElementGuid>ad59865a-1d4d-4134-85ad-191b7dd92d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://web.whatsapp.com/send/?phone=918860402452&amp;text=hi')]</value>
      <webElementGuid>4657e46a-472e-49dc-b688-12658d78cbf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/a</value>
      <webElementGuid>a18be762-939b-40bb-b501-0bc8148d818f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://web.whatsapp.com/send/?phone=918860402452&amp;text=hi' and @title = 'Share on WhatsApp' and @id = 'action-button' and (text() = 'Continue to Chat' or . = 'Continue to Chat')]</value>
      <webElementGuid>987920b5-0631-49e5-a4b8-ddf7e63089fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
