<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Help us with your city_city_name</name>
   <tag></tag>
   <elementGuidId>efec0c82-f2c7-4a7e-920b-a258f8aaf4bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#city_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='city_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>938b7933-f343-465d-9fd3-0e0a4ed096c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>city_name</value>
      <webElementGuid>240dbd03-3715-4595-8b7e-155a973f0fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city_name</value>
      <webElementGuid>12b55b47-819f-478b-999a-7617d10aa1cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-input animate_label</value>
      <webElementGuid>c834dc3a-d65a-49e2-8c1d-87da8bd08bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70fdfc5f-18a7-4e71-8950-ab84c92ec772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>b6672123-efec-47b4-b09d-323f5123f665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocusout</name>
      <type>Main</type>
      <value>getQuoteCity(this.value)</value>
      <webElementGuid>efca99da-5913-4baf-98f5-a0fe2e977697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;city_name&quot;)</value>
      <webElementGuid>89ac3490-7d99-446d-8d54-b0b57fb29ffb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='city_name']</value>
      <webElementGuid>d1e65376-aa5d-4cd9-9e0d-ac56f4b2eb64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='care-quote-box']/div[4]/div[2]/div/div/input</value>
      <webElementGuid>cdf13c54-5599-45dc-a18a-8872e3c1f0d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
      <webElementGuid>7fdf5efb-d81c-4489-9feb-7b14b1ef91a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'city_name' and @name = 'city_name' and @type = 'text']</value>
      <webElementGuid>25e56214-0639-4aa0-9757-0e65642ea89f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
