<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AADHAR NO_aadhar_no</name>
   <tag></tag>
   <elementGuidId>d6fe89ab-f114-45d0-a098-7682cb3dce8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='aadhar_no']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#aadhar_no</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b549f98-c273-414e-a79d-fd19b4892fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>5c86ce42-e478-4d41-bdfe-3f38d4a57dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>141a5bf3-b1cb-4299-af7e-e852e457b770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>bc8db7c0-e824-42a2-a72b-e95fd282cb9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return isNumber(event,this,4);</value>
      <webElementGuid>093532f9-34a3-45c2-ab53-2053e41d2eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>return isNumber(event,this,4);</value>
      <webElementGuid>5940ac35-b576-4766-b0da-2a533f4b1e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aadhar_no</value>
      <webElementGuid>6af4d9cd-c9ca-460e-b6b6-5dd26535b4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>aadhar_no</value>
      <webElementGuid>4e1aa5a5-6d2c-4d08-84fc-788c24479dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Last 4 digits of Aadhar</value>
      <webElementGuid>b4ce43f4-7e47-465a-9655-9fe509ec6343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input aadhar_no</value>
      <webElementGuid>0d2817d7-28b9-45e0-9407-b2585e36ca98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kyc_container&quot;)/div[@class=&quot;kyc_details_cont adhar_card_details&quot;]/div[@class=&quot;kyc_details_wrapper&quot;]/div[@class=&quot;form_flex&quot;]/div[@class=&quot;column&quot;]/div[@class=&quot;common_input&quot;]/div[@class=&quot;form_input borderdinput focus_border&quot;]/div[@class=&quot;floating-label&quot;]/input[@id=&quot;aadhar_no&quot;]</value>
      <webElementGuid>694231ef-ee29-4041-aa59-6b7a75ea054d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='aadhar_no']</value>
      <webElementGuid>489452be-712e-40cc-bf74-f2a8a0ab0ce3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kyc_container']/div[3]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>039defb4-926f-4bb2-bbea-45bb797922fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>36c3ddfe-108d-481c-a6ad-1a07373b4fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'aadhar_no' and @name = 'aadhar_no' and @placeholder = 'Enter Last 4 digits of Aadhar']</value>
      <webElementGuid>d7e75898-ca1f-4d39-8dcf-2790c15c0a6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
