<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Blog</name>
   <tag></tag>
   <elementGuidId>7ae1633a-e9d4-449f-b20c-4871f7455709</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;headerOtherSingle('about us')&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4bafa3d4-09dd-4dd2-9e0f-526fea79661f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu-item-link</value>
      <webElementGuid>7e259d82-1ac6-4cbe-9069-25cb358108ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.careinsurance.com/blog/</value>
      <webElementGuid>bfefbccc-fa2b-4add-9eea-f4dee2d4af91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>headerOtherSingle('about us')</value>
      <webElementGuid>709fad8b-d258-434c-a520-b39ff0c08d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Blog</value>
      <webElementGuid>f5002acd-0fa0-4b89-9d02-ca0ffd4a02d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;care_page common_page_body category_page Chrome_view&quot;]/header[@class=&quot;navbar-main resolution_container&quot;]/div[@class=&quot;header-right&quot;]/div[@class=&quot;menu-wrapper&quot;]/div[@class=&quot;menu_list-wrapper&quot;]/div[@class=&quot;menu_list-container&quot;]/div[@class=&quot;menu_list&quot;]/div[@class=&quot;menu-items-box&quot;]/ul[1]/li[@class=&quot;menu-item mob-menu-bottom-border&quot;]/a[@class=&quot;menu-item-link&quot;]</value>
      <webElementGuid>e426403d-9989-415d-a630-07a54eedb00e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;headerOtherSingle('about us')&quot;]</value>
      <webElementGuid>c1451eaa-b15a-48fc-abdc-1da11e28e8b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Blog')]</value>
      <webElementGuid>b0d1ae33-213b-48e1-8719-1de794d873ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Renew'])[1]/following::a[1]</value>
      <webElementGuid>314ac80a-1691-4996-8058-47557dd4b4cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unclaimed Amount'])[1]/following::a[2]</value>
      <webElementGuid>81bf1dc4-764b-45ea-ba7f-f366f02224e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Portability'])[1]/preceding::a[1]</value>
      <webElementGuid>206f66a1-a859-4eea-b637-277e42689187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='contact us'])[1]/preceding::a[2]</value>
      <webElementGuid>949c501c-a0f2-4418-9de7-9efcf1408650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Blog']/parent::*</value>
      <webElementGuid>0489268d-34d1-44ef-8a6d-78d3eed93c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.careinsurance.com/blog/')]</value>
      <webElementGuid>17066289-7e98-4e82-85bd-7e63e3039cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>57f58932-05c2-476c-9f41-da9a2c099296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.careinsurance.com/blog/' and (text() = 'Blog' or . = 'Blog')]</value>
      <webElementGuid>1d611ed1-cf2f-4f9b-adae-9e679b9a1b9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
