<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Download the Care Health Insurance - Cu_d02ecd</name>
   <tag></tag>
   <elementGuidId>cbdf5c40-4f93-403f-b100-a0826c8700ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='app_download']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p.app_iocn > img.lozad</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fb0eaf25-592a-4d9a-b5bb-a5e76acd3a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>254</value>
      <webElementGuid>ad84355a-fe82-4ec6-9693-28248acba5e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>ba32522d-38d7-42ee-9dd0-ca248236154a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lozad</value>
      <webElementGuid>2185f17a-8a56-47f2-9cc8-0261207ea913</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>app_download</value>
      <webElementGuid>1b832927-968f-4165-af6b-0c534a8dadc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>app_download</value>
      <webElementGuid>463760af-3976-46fc-823d-33aeb5f8ceb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.careinsurance.com/assets/images/shpimg/Mobile_App.png</value>
      <webElementGuid>764d9998-7a6f-4342-8fee-ec21f304e9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.careinsurance.com/assets/images/shpimg/Mobile_App.png</value>
      <webElementGuid>99f496b9-ecc8-408f-93ac-2f7876b204b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7f52c74e-c410-460e-b14c-0e5b473446d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;cards_show Chrome_view&quot;]/section[@class=&quot;support_cont&quot;]/div[@class=&quot;custom_container&quot;]/div[@class=&quot;support_details_section&quot;]/div[@class=&quot;support_method&quot;]/div[@class=&quot;step_container&quot;]/div[@class=&quot;help_details flex_div&quot;]/div[@class=&quot;app_download&quot;]/div[@class=&quot;ios_android_icon&quot;]/p[@class=&quot;app_iocn&quot;]/img[@class=&quot;lozad&quot;]</value>
      <webElementGuid>4d06d2d3-e0db-4a35-a2c0-0e9675b05e6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='app_download']</value>
      <webElementGuid>9684f574-ae32-43f4-978b-c282151e3a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/img</value>
      <webElementGuid>848510a9-39aa-4872-ac69-88b2035177d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'app_download' and @title = 'app_download' and @src = 'https://www.careinsurance.com/assets/images/shpimg/Mobile_App.png']</value>
      <webElementGuid>e16e96a3-1542-403d-b62a-2af1d6c6937a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
