<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_What are the 7 Steps of CPR_lozad</name>
   <tag></tag>
   <elementGuidId>5e5b6191-37f1-454c-9446-b15b7263ad30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='blog-body']/p[13]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(13) > img.lozad</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>793fe9a1-be5d-4721-8179-d47004e2a6be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lozad</value>
      <webElementGuid>d957c6c3-ea33-4335-bb0f-72f4a21de814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>CPR for adults</value>
      <webElementGuid>617c14c8-22f4-43a8-8265-dc4177673952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>CPR for adults</value>
      <webElementGuid>53964c53-1d54-4856-97cb-e3459cf0e0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>660</value>
      <webElementGuid>0a3a17ee-01c0-4d12-8892-5b63001b25b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>282</value>
      <webElementGuid>f4c9b674-2722-4e88-820d-cbe580cc6f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.careinsurance.com/upload_master/media/how-to-give-cpr.webp</value>
      <webElementGuid>d5e8c367-6fd9-4936-bc86-09496ffa3852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.careinsurance.com/upload_master/media/how-to-give-cpr.webp</value>
      <webElementGuid>7733d0e3-70b4-4155-a1bc-e0fc34eb1177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>63d8532e-425b-4d1c-bd04-9f6f7277f2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;blog-body&quot;)/p[13]/img[@class=&quot;lozad&quot;]</value>
      <webElementGuid>b392ab02-0d93-4402-ae92-4f7fbe560f5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='blog-body']/p[13]/img</value>
      <webElementGuid>2d2473e5-f48b-41f2-929f-eb8c39e11575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='CPR for adults']</value>
      <webElementGuid>84579d86-060d-472f-ba60-0fb6f59c15be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[13]/img</value>
      <webElementGuid>e54c615d-adc5-408f-8337-54f2d198f194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'CPR for adults' and @alt = 'CPR for adults' and @src = 'https://www.careinsurance.com/upload_master/media/how-to-give-cpr.webp']</value>
      <webElementGuid>33e9ff0f-95d0-4c12-a1d6-408b0674848e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
