<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img__lozad care_spritepencil-icon</name>
   <tag></tag>
   <elementGuidId>8e98949b-8ec1-448c-8b29-58b0343619db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='offers_policy']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.lozad.care_spritepencil-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b88d04cc-ab40-4630-9ee2-e5845eac0313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>edit</value>
      <webElementGuid>d880703e-bfaf-4a1f-88b7-8cf2ec32b020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>edit</value>
      <webElementGuid>b65cd688-f2e4-4a15-9db2-06f848bebc62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>092d2b4e-9129-4c70-95b5-a4beba2b3af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>baf20a7f-4044-40a6-ab28-5ccfa3280fb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lozad care_spritepencil-icon</value>
      <webElementGuid>723b2173-8969-422a-aa30-1002c6b5452c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://www.careinsurance.com/cpproject/rhiclfrontend/assets/public/images/pencil_icon.svg</value>
      <webElementGuid>40a4b6aa-7d90-444f-8c0e-865cbab92007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.careinsurance.com/cpproject/rhiclfrontend/assets/public/images/pencil_icon.svg</value>
      <webElementGuid>a2ef7364-6fa6-4cdc-8f7e-bb7b474c5cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loaded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>92950435-e573-4581-a857-1ab687b0ef8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;offers_policy&quot;)/img[@class=&quot;lozad care_spritepencil-icon&quot;]</value>
      <webElementGuid>4f52c3cb-e1a8-43d0-8c6e-7555d174ec8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='offers_policy']/img</value>
      <webElementGuid>8d318b12-dc38-4d43-b847-d6979d771d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='edit']</value>
      <webElementGuid>3fa73505-e24d-4554-b5dc-12d7cd14cef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/img</value>
      <webElementGuid>2e230226-a931-435e-a61b-8ed614767bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'edit' and @title = 'edit' and @src = 'https://www.careinsurance.com/cpproject/rhiclfrontend/assets/public/images/pencil_icon.svg']</value>
      <webElementGuid>7f7a80ee-43b8-4782-a842-552a556adb5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
