<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_0</name>
   <tag></tag>
   <elementGuidId>c114d3e4-bbb2-4b20-b3ad-c9b820cfc4da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='premium_form']/div/div/div[2]/div/div/div[2]/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.first_label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>9507f344-6610-48ad-8eaa-bd972e6b283d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>adult0</value>
      <webElementGuid>654cb507-7b10-46ec-aa1a-dc646e613eee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>first_label</value>
      <webElementGuid>15929039-16fd-4a5b-bf29-647ab226183d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>21d0506b-6a86-46cf-b929-4984d1b4d273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;premium_form&quot;)/div[@class=&quot;left_sec&quot;]/div[@class=&quot;panel_cont Cr-PreQuote-InsuredDetails carestepCompleted active&quot;]/div[@class=&quot;panel 2_panel insured_person&quot;]/div[@class=&quot;panel_content form_enable&quot;]/div[@class=&quot;panel_cont_inner dropdown_up insured_person_selection&quot;]/div[@class=&quot;selected_members light_bg text_cntr&quot;]/div[@class=&quot;radio_group_member&quot;]/label[@class=&quot;first_label&quot;]</value>
      <webElementGuid>18e61ef5-5819-4d99-b818-920cef1ed256</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='premium_form']/div/div/div[2]/div/div/div[2]/div/label</value>
      <webElementGuid>13304dc7-e270-410e-860d-26d536c9af77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Female'])[1]/following::label[1]</value>
      <webElementGuid>e0d80774-74e2-46ea-8e0a-0645c7b11932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Male'])[1]/following::label[2]</value>
      <webElementGuid>2873105e-41f8-4d6d-bcde-35802bea72a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✔'])[2]/preceding::label[8]</value>
      <webElementGuid>238fcb7b-bac6-4ac2-9988-71c3ec09003f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='World Wide'])[1]/preceding::label[8]</value>
      <webElementGuid>debc8222-0f00-4066-9870-a44412fef800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0']/parent::*</value>
      <webElementGuid>de77926c-5afc-460f-9de3-7178d883ba4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/label</value>
      <webElementGuid>87133bc2-6383-4147-a5e6-1b2f9042a97b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '0' or . = '0')]</value>
      <webElementGuid>9625ba68-97b2-44cb-ae2e-33b94777e99f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
