<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Female_loking_inure_dot</name>
   <tag></tag>
   <elementGuidId>3b832767-3db3-453c-b773-365569aefc0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='premium_form']/div/div/div[2]/div/div/p/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.loking_inure_dot</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>91ca98f9-1c28-4b3a-80c2-c2ad737b1d4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loking_inure_dot</value>
      <webElementGuid>f0b24990-fb32-4c30-96d1-447e5be30ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;premium_form&quot;)/div[@class=&quot;left_sec&quot;]/div[@class=&quot;panel_cont Cr-PreQuote-InsuredDetails carestepCompleted active&quot;]/div[@class=&quot;panel 2_panel insured_person&quot;]/div[@class=&quot;panel_content form_enable&quot;]/div[@class=&quot;panel_cont_inner dropdown_up insured_person_selection&quot;]/p[@class=&quot;second_heading dot_label&quot;]/span[@class=&quot;loking_inure_dot&quot;]</value>
      <webElementGuid>148de4fe-6609-4de2-bb36-13e3e326c27b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='premium_form']/div/div/div[2]/div/div/p/span</value>
      <webElementGuid>e210d569-af64-40d3-8cea-aabd39adbfca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/p/span</value>
      <webElementGuid>93e1c51e-7226-456a-94df-beeb0fdc2ae0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
