<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_</name>
   <tag></tag>
   <elementGuidId>c84f34f0-ca0f-456f-81d4-6b911638936b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@onclick=&quot;closePopup('ADONS')&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addon_coverage_quotebox > div.modal-content > div.modal-inner-content > span.close1.comon_close_btn.sec_popup</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>79e9e042-1272-44dc-8950-07a1788d5a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close1 comon_close_btn sec_popup</value>
      <webElementGuid>c6fba80e-8baf-4577-a1ba-269e85da8a94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>closePopup('ADONS')</value>
      <webElementGuid>9b2fc230-928f-4cff-81dc-ba5cbef17a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>2a54281e-f442-42b6-8cd2-d6667c2132f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addon_coverage_quotebox&quot;)/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-inner-content&quot;]/span[@class=&quot;close1 comon_close_btn sec_popup&quot;]</value>
      <webElementGuid>133856fc-c51e-46b0-b265-434c0314c6cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@onclick=&quot;closePopup('ADONS')&quot;]</value>
      <webElementGuid>bd0a2bde-5709-424c-96c8-82d9a210dec5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='addon_coverage_quotebox']/div/div/span</value>
      <webElementGuid>87246cd6-5114-4402-a89c-551337a50ef9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Done'])[3]/following::span[1]</value>
      <webElementGuid>1085f07e-ffce-4326-9c6a-c9700a7d18ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The proposal has been sent!'])[1]/following::span[1]</value>
      <webElementGuid>b29d3854-1bb2-4c59-b624-e10eecea82cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/span</value>
      <webElementGuid>9cb26f23-dc29-43ee-aa0f-2401d9e6a69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '×' or . = '×')]</value>
      <webElementGuid>d7abf8c2-affc-4610-8bc3-d001bd265d43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
