<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DATE OF BIRTH_aadhar_dob</name>
   <tag></tag>
   <elementGuidId>2d6a7528-a617-4a07-9b2a-f836f9e0ffce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aadhar_dob</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='aadhar_dob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d37b933f-7339-4500-b025-ae92136494ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>05dd66e5-a431-4c0c-9544-ec6df4a6adc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d4d6bc1f-721e-467d-8afd-45ad58f20f47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aadhar_dob</value>
      <webElementGuid>7c56c2ff-e210-4064-8e5b-d6d73a2d26cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>aadhar_dob</value>
      <webElementGuid>91c1f78c-de83-472d-860f-0cf8d6a18b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>187bbdc4-74d2-498e-b471-1221305f00ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD / MM / YYYY</value>
      <webElementGuid>07775c5a-b963-41be-b7be-959b4c4406d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input aadhar_dob</value>
      <webElementGuid>83e27b9b-6676-4959-950f-08677538fbb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kyc_container&quot;)/div[@class=&quot;kyc_details_cont adhar_card_details&quot;]/div[@class=&quot;kyc_details_wrapper&quot;]/div[@class=&quot;form_flex&quot;]/div[@class=&quot;column&quot;]/div[@class=&quot;common_input&quot;]/div[@class=&quot;form_input borderdinput&quot;]/div[@class=&quot;floating-label&quot;]/input[@id=&quot;aadhar_dob&quot;]</value>
      <webElementGuid>f363e0c7-623f-476d-b4b7-b2db2ef200ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='aadhar_dob']</value>
      <webElementGuid>7b44c061-ebf3-4d13-b27f-fa0f981d6f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kyc_container']/div[3]/div/div/div[4]/div/div/div/input</value>
      <webElementGuid>87345991-a050-49e2-9718-df07bf4be93f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[4]/div/div/div/input</value>
      <webElementGuid>35c2c4f2-a5cc-496f-93a8-9a026ba55a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'aadhar_dob' and @name = 'aadhar_dob' and @placeholder = 'DD / MM / YYYY']</value>
      <webElementGuid>bff8588a-53c0-4ee0-9e4d-1964e9c7cec1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
