<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FULL NAME AS PER AADHAR_aadhar_name</name>
   <tag></tag>
   <elementGuidId>5a3ab36e-9da4-4f64-9d3e-e13569b4b0f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aadhar_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='aadhar_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f95595e-4fee-44bc-ab5a-cdeec51b1037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>d1e62f04-6a38-4ab3-adbc-7cca8d044102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f42dde47-cfdf-4013-a7ff-7744bef05d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aadhar_name</value>
      <webElementGuid>7276d55b-1380-4b1d-bcd2-8cbf368bf6d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>aadhar_name</value>
      <webElementGuid>b47cc9dd-a6a9-4235-9128-709dfe8da07d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter name as per Aadhar</value>
      <webElementGuid>33909faf-60b0-40a2-bff4-ac7c7d6db876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input aadhar_name</value>
      <webElementGuid>1eb6deb8-7b86-4fce-9520-f046558aa761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kyc_container&quot;)/div[@class=&quot;kyc_details_cont adhar_card_details&quot;]/div[@class=&quot;kyc_details_wrapper&quot;]/div[@class=&quot;form_flex&quot;]/div[@class=&quot;column&quot;]/div[@class=&quot;common_input&quot;]/div[@class=&quot;form_input borderdinput&quot;]/div[@class=&quot;floating-label&quot;]/input[@id=&quot;aadhar_name&quot;]</value>
      <webElementGuid>70d09505-3b49-4c42-98de-183af81eb852</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='aadhar_name']</value>
      <webElementGuid>41a83991-6deb-4f7e-8780-1f5723985e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kyc_container']/div[3]/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>a6c28ec3-514b-46da-8314-1164222a0bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>414d3fcb-9985-49c7-86b0-c00aecdc7b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'aadhar_name' and @name = 'aadhar_name' and @placeholder = 'Enter name as per Aadhar']</value>
      <webElementGuid>ba82d7f2-3664-41b5-9faa-ebe9730bfc44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
