<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Aadhaar ( Last 4 digits of Aadhaar )_r_8eb722</name>
   <tag></tag>
   <elementGuidId>63ce2913-2c69-4a7f-9975-084704ca3993</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.kyc_item.ekyc_adhar_card > span.radio_checkmark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kyc_container']/div/label[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a5041f61-23de-419d-bc7f-28558d7eb05f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio_checkmark</value>
      <webElementGuid>47cf553e-a882-4774-9f76-e8de12d89a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kyc_container&quot;)/div[@class=&quot;kyc_options&quot;]/label[@class=&quot;kyc_item ekyc_adhar_card&quot;]/span[@class=&quot;radio_checkmark&quot;]</value>
      <webElementGuid>9c3b335d-fbf3-42b2-881b-8381721733af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kyc_container']/div/label[2]/span</value>
      <webElementGuid>221af0ff-5872-42e6-83b8-af61c3b10c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label[2]/span</value>
      <webElementGuid>04f141a3-a281-4b3f-b086-c4e74db7a61d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
