<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_VERIFY</name>
   <tag></tag>
   <elementGuidId>f148ac23-755b-4b83-9fbb-ab501af25212</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.kyc_details_cont.adhar_card_details > div.kyc_details_wrapper > div.form_flex > div.verify_btn_wrap > button.verify_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kyc_container']/div[3]/div/div/div[5]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>965c1117-7815-44f7-aff0-c2b374817b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>verify_btn</value>
      <webElementGuid>34c10200-4637-4095-b433-c7b3c2335f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>6f1c524a-aa81-45b6-9aed-cc3de8a4c7b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VERIFY</value>
      <webElementGuid>88c224c5-0e2d-40a7-a935-e3ea124a3fd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kyc_container&quot;)/div[@class=&quot;kyc_details_cont adhar_card_details&quot;]/div[@class=&quot;kyc_details_wrapper&quot;]/div[@class=&quot;form_flex&quot;]/div[@class=&quot;verify_btn_wrap&quot;]/button[@class=&quot;verify_btn&quot;]</value>
      <webElementGuid>502b34ef-c2de-44cf-9083-8d2bafcf8859</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kyc_container']/div[3]/div/div/div[5]/button</value>
      <webElementGuid>d358ee35-f7a2-4a66-b6d4-722b99d0eaef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please provide DOB'])[1]/following::button[1]</value>
      <webElementGuid>b7938431-1cbe-4feb-bdb8-bae906c495da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DATE OF BIRTH'])[2]/following::button[1]</value>
      <webElementGuid>a8c73500-886d-4d82-975f-6af8f1d8afa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verification Successful!'])[2]/preceding::button[1]</value>
      <webElementGuid>2040fc75-946d-4fd6-8c6f-bf37deea385b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Verification failed please re-enter the correct info and verify again'])[2]/preceding::button[1]</value>
      <webElementGuid>2ffa5331-c318-43e5-8d6c-de65df5d826d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[5]/button</value>
      <webElementGuid>951d399f-057f-46ea-8a37-46adf4121d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'VERIFY' or . = 'VERIFY')]</value>
      <webElementGuid>e112155b-b671-47fb-a2b2-0ff5af92b276</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
