<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FULL NAME AS PER AADHAR_aadhar_name</name>
   <tag></tag>
   <elementGuidId>ee3ce632-f800-46bd-987d-ecd22a05edd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aadhar_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='aadhar_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51875f63-063e-487b-a4dd-09f902fa1d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>bed42fca-5e88-46a2-80dd-3061eb8834ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8b017735-f8a8-4ec8-a91e-3d42ec06368f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aadhar_name</value>
      <webElementGuid>070be3c1-1176-48be-82a4-a43cba8ff641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>aadhar_name</value>
      <webElementGuid>2f617114-ccc6-434c-83c3-2baaa2d9460c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter name as per Aadhar</value>
      <webElementGuid>b067d303-e189-43e6-b092-821b40690869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Saiteja Thalluru</value>
      <webElementGuid>351eb18c-b04b-4b64-8125-a9007964d4e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input aadhar_name</value>
      <webElementGuid>98cf083c-5d5e-43c5-ae04-1a0e5f4c68d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aadhar_name&quot;)</value>
      <webElementGuid>d3119447-54ae-41e9-97f5-b1bb9799d322</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='aadhar_name']</value>
      <webElementGuid>9db88c1f-a858-47c5-801e-b840965742eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kyc_container']/div[3]/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>1c9eb3eb-068d-4e8b-b707-dbf1b26d8b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>a27f42e0-ea5a-4c45-bfaa-4238d0e993ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'aadhar_name' and @name = 'aadhar_name' and @placeholder = 'Enter name as per Aadhar']</value>
      <webElementGuid>f5e65907-8dc9-4dbb-ba45-85d885b8a51f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
