<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Same as permanent address_cores_address</name>
   <tag></tag>
   <elementGuidId>c221e5cb-1096-438c-be15-9435c9d1a7f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cores_address_same_as</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cores_address_same_as']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>858c5d3f-599a-44ae-99ad-da28781cf2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d798b8b7-dc5f-46e4-b476-a489c709f78e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cores_address</value>
      <webElementGuid>26a0de09-d760-44bb-b4ce-d6ca147a5e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cores_address_same_as</value>
      <webElementGuid>f7cc9b87-bb7e-4cc2-9a9b-6ac8b7a8856e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cores_address</value>
      <webElementGuid>c1e12827-fb0b-490d-b755-0a0fa91f200a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>5e02928e-c169-4ea6-8292-524d52088c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cores_address_same_as&quot;)</value>
      <webElementGuid>10427b96-de55-4b45-ad4a-f36aaaa1e183</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cores_address_same_as']</value>
      <webElementGuid>91cd442c-b7ec-4bb6-b49b-d5b1b8bfe084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='proposer_details']/section/div/div/div[5]/div[2]/div/input</value>
      <webElementGuid>9d10bf7a-2991-4ae6-8ba0-257a9fa8b00c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/input</value>
      <webElementGuid>186a7bd2-779c-4f19-afdf-59cf93f4d8ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'cores_address' and @id = 'cores_address_same_as']</value>
      <webElementGuid>c691ba56-614e-422d-9a72-8f3142699903</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
