<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Landmark_landmark</name>
   <tag></tag>
   <elementGuidId>61e55d41-e3ff-4d92-9497-dd9cc932faa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#landmark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='landmark']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>16859398-ca06-4f9b-b8e4-7343fd3070d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d57dd427-a45a-48da-80f8-57220a017b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>15f11ac2-35a2-4550-9fda-f329ea414219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>landmark</value>
      <webElementGuid>362e9f2c-8036-434a-998c-a17b8a1b76e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>landmark</value>
      <webElementGuid>0cec75f3-33cd-4b25-8fea-45988265f7e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type here</value>
      <webElementGuid>db7cbb32-022f-4580-b623-397d09c70823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input landmark</value>
      <webElementGuid>7d761ad8-8e3a-484f-8005-de62215ce05e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>a4296365-c7d1-436e-a97e-3e48f53338d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;landmark&quot;)</value>
      <webElementGuid>86b520a7-ebe0-4772-9c6a-bfb69d9a4371</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='landmark']</value>
      <webElementGuid>01914bb9-b282-47e4-93ae-7b2ffb6d6b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='proposer_details']/section/div/div/div[4]/div[2]/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>3b75349d-dfaf-40f3-861d-51d80df1d1ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>680957b0-188b-46f8-8aa7-b643225b97da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'landmark' and @id = 'landmark' and @placeholder = 'Type here']</value>
      <webElementGuid>764a3965-8733-48f5-a956-3429878732d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
