<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nominee DOB_nomineeDob</name>
   <tag></tag>
   <elementGuidId>d78e1a26-5462-4988-8a2b-1a7bdb2550fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nomineeDob</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nomineeDob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85851e58-be4e-400b-9fec-93b5599a0a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>04d361ed-05dc-46ca-80b5-db3bb424e87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nomineeDob</value>
      <webElementGuid>dc53b519-9b6e-4a52-906e-0416f64706f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nomineeDob</value>
      <webElementGuid>d108801a-7ff9-45c5-bfde-dd0586c4c907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD / MM / YYYY</value>
      <webElementGuid>ce42ccba-2438-4722-93cf-6ab38278b439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input calendar_input_nominee calender_datepicker_input dob nomineeDob hasDatepicker</value>
      <webElementGuid>823deb6a-5057-477a-9143-f6b23fc8b72b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>e14b4f7e-021c-495a-a06d-6630698d7ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>b48314a1-f15e-403b-9b8d-9f78ed9cbd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>checkForNominee();</value>
      <webElementGuid>42ba767f-a6e7-4d5b-b022-0ea815b79866</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nomineeDob&quot;)</value>
      <webElementGuid>30f5dd38-c393-4cd5-8560-7d7085f4e707</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nomineeDob']</value>
      <webElementGuid>bf7363f7-5b09-41d9-b1c7-2800ea0e07e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='proposer_details']/section/div/div/div[6]/div[2]/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>d6b0a86a-aba0-4c28-8530-8c13f1535bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>82e63a04-759d-4f40-9cd7-7d2de3fe42e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'nomineeDob' and @id = 'nomineeDob' and @placeholder = 'DD / MM / YYYY']</value>
      <webElementGuid>11b80423-983d-4844-b86d-a4278b1185cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
