<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Weight_insured_members1weight</name>
   <tag></tag>
   <elementGuidId>671385e7-481d-484c-8a11-060242377aa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#weight_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='weight_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>30a9800b-9699-463d-85f9-bf37baea3958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f136f4d6-ae5c-4fd7-b25f-4d457f6718c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>2109174d-3628-48bd-a4c5-9cadaae87625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>insured_members[1][weight]</value>
      <webElementGuid>bb1a4c41-3739-4810-841a-2c1aa33ced3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>weight_1</value>
      <webElementGuid>60fd7d0d-58c9-4dd2-b3ed-f91bde1cf5b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>in kgs</value>
      <webElementGuid>48d45883-9fa6-488f-845d-7f73ad8636a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input insured_members insured_members_weight valid</value>
      <webElementGuid>9341e42b-661c-4eca-8376-ffcfd5c3651c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>afda1178-906f-4a3d-8d32-1aa01b62b0bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>return isNumber(event, this, 3);</value>
      <webElementGuid>b71957f2-e3a0-4fe3-91f7-3bbde53f82ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;weight_1&quot;)</value>
      <webElementGuid>a8cd21aa-6cd5-48f2-93b4-87a3694d79eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='weight_1']</value>
      <webElementGuid>f1b76b9a-ad5d-4408-971a-630a0ae5f186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insured_details']/section/div/div/div/div/div/div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>204a8773-2a04-4fdf-8a43-6236cb6411f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[3]/div[2]/div/div/div/input</value>
      <webElementGuid>828b8ff4-1c9f-41a1-aff5-92d8c119bea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'insured_members[1][weight]' and @id = 'weight_1' and @placeholder = 'in kgs']</value>
      <webElementGuid>a3be13dd-d61c-4ac3-82a6-e382c2806fc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
