<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Emergency Contact No_EmergencyMobileNumber</name>
   <tag></tag>
   <elementGuidId>526ba163-9d59-40d0-b0aa-18a5fe073626</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EmergencyMobileNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EmergencyMobileNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>836dd4f6-86cc-44e9-ae51-f9536b67132e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EmergencyMobileNumber</value>
      <webElementGuid>f4372f46-3b94-47bb-b344-3731636c27a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EmergencyMobileNumber</value>
      <webElementGuid>5abdcc22-cc22-43e2-8856-8013f55778da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>334e1619-162f-49e5-8906-c456df9dde8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>711e6c5b-93c3-4b3d-918a-7bfa571ada7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input EmergencyMobileNumber</value>
      <webElementGuid>fe2bc7e8-1d0e-481e-9ad0-4c2a7749b910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter contact no</value>
      <webElementGuid>84bd53b9-974b-4a00-bf03-66d4f501ef73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>return isNumber(event, this, 10);</value>
      <webElementGuid>120f1e4b-d31c-4eb0-a38d-c5f4fcaec95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EmergencyMobileNumber&quot;)</value>
      <webElementGuid>73386791-6eb3-4c91-9f11-d542a3ad2576</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EmergencyMobileNumber']</value>
      <webElementGuid>57faa3f5-c979-4477-b91b-d18cc3853794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='proposer_details']/section/div/div/div[3]/div[2]/div/div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>0aea0619-de76-49a5-ba20-36a3596c9d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/input</value>
      <webElementGuid>123b9e51-7f51-4b24-9b5f-53ca5c03af50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'EmergencyMobileNumber' and @id = 'EmergencyMobileNumber' and @type = 'tel' and @placeholder = 'Enter contact no']</value>
      <webElementGuid>cfdf4505-3c00-4010-9339-af8d35a068bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
