<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_nominee_name</name>
   <tag></tag>
   <elementGuidId>3caf80c2-de2b-442a-b208-efe876370656</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nominee_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nominee_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a6d6f32-a18e-4f16-83d0-77378fffecab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>47f33f8d-a7ce-4f5d-a7d1-f48c0cda64fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9cb6d00-6da2-4c5d-b188-9eba13971bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nominee_name</value>
      <webElementGuid>24afd088-f826-46b0-b747-c88b556b96cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nominee_name</value>
      <webElementGuid>d1517796-5575-410c-8e82-0075b4c13e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>return validName(this);</value>
      <webElementGuid>f2510cc2-a392-4dc9-a821-3f9bf6b88a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nominee Name</value>
      <webElementGuid>975a68bb-2e76-4eba-828f-26ed66a66756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input nominee_name</value>
      <webElementGuid>7979b838-4a6a-4ca3-bfe0-5c12df1129d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nominee_name&quot;)</value>
      <webElementGuid>4ad45cfc-2400-4c14-86dd-1f39ec8c113c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nominee_name']</value>
      <webElementGuid>682df46f-b4a0-4ef3-8e79-c2069f31ac3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='proposer_details']/section/div/div/div[6]/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>fc48540d-32f5-423b-b528-285b1219b11a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/div/div/div/div/input</value>
      <webElementGuid>2a219e18-378b-4d6a-a6f9-7f7dde640134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nominee_name' and @id = 'nominee_name' and @placeholder = 'Nominee Name']</value>
      <webElementGuid>03d0aff0-d433-41ca-867c-aadd3edfde07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
