<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__insured_members1height_inches</name>
   <tag></tag>
   <elementGuidId>e357b6ee-91f8-4cec-b897-bda21044c64d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#height_inches_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='height_inches_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24535649-74c1-4528-9d53-1357a7c02b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>ffb3a9b1-b2ed-49da-9bd0-8a74387e63fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>072d1797-6a93-4939-8cca-ec78bf80880a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>insured_members[1][height_inches]</value>
      <webElementGuid>6a36444e-81d9-45c4-b267-3fbf22f5979c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>height_inches_1</value>
      <webElementGuid>3372db34-35e9-4bcf-9c7b-e6822fe855ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Inches</value>
      <webElementGuid>1d699d53-ccac-4e28-b75d-b569bb74004c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input insured_members insured_members_heightInches valid</value>
      <webElementGuid>01650dc3-aba9-405c-8daf-e8c58ec314e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>3897b044-6c11-46c4-b64c-a537302deb96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>return isNumber(event,this,2);</value>
      <webElementGuid>ab22defd-b478-4445-969b-51665af30215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;height_inches_1&quot;)</value>
      <webElementGuid>9e60e8a0-7b31-42e4-821d-f42ef8380b7a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='height_inches_1']</value>
      <webElementGuid>194fcd36-3ced-4dca-a2d0-f98fbe71e961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insured_details']/section/div/div/div/div/div/div[3]/div/div/div/div/div[3]/input</value>
      <webElementGuid>99387296-c5c6-491a-b7c3-bcdfc4628814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[3]/input</value>
      <webElementGuid>571b276c-7246-4eab-9e54-306d2b0ddfd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'insured_members[1][height_inches]' and @id = 'height_inches_1' and @placeholder = 'Inches']</value>
      <webElementGuid>f30a11ff-d304-4f14-9076-6d05659c4232</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
