<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Height_insured_members1height_feet</name>
   <tag></tag>
   <elementGuidId>4c581a63-16d6-4d62-8627-23cfa9479518</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#height_feet_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='height_feet_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bce469f-1c3f-4d80-b0b8-df74421d4d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>28475975-acbc-440e-aa6b-26cbf52e5356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>a0accd13-b799-4fcb-bee6-99293ef95d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>insured_members[1][height_feet]</value>
      <webElementGuid>88a0b8af-9afb-4fe0-8c21-d44237141f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>height_feet_1</value>
      <webElementGuid>27ba265d-8ab9-4356-b0a1-3b5d56e85f39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Feet</value>
      <webElementGuid>04ff99c1-bc55-4516-8e87-7d900dd50f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input insured_members text_right insured_members_heightFeet valid</value>
      <webElementGuid>f8cabbc9-774b-4c85-8a8c-5c8c212dba09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1f67f32f-6008-404b-8e03-87dda6a5f7cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>return isNumber(event,this,2);</value>
      <webElementGuid>12d33c2c-3af1-4e27-8c47-8368489d7130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;height_feet_1&quot;)</value>
      <webElementGuid>75978127-11b6-4698-9e75-75e1984db8c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='height_feet_1']</value>
      <webElementGuid>31365456-c8f4-447b-a2a5-4f90612aa538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insured_details']/section/div/div/div/div/div/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>99081e43-0f2c-42e7-a4b1-9995f8ebdd79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[3]/div/div/div/div/div/input</value>
      <webElementGuid>f5cedeec-5daa-4c96-b5fc-6976fc722fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'insured_members[1][height_feet]' and @id = 'height_feet_1' and @placeholder = 'Feet']</value>
      <webElementGuid>bd6067f0-8702-45a7-91dd-772b559c3f5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
