<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_email_id</name>
   <tag></tag>
   <elementGuidId>75882c00-bea8-4dc2-ad69-403b9bc7c3a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9096ac06-5af8-483a-ac76-f787506710f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>2d433c05-72b0-4c1b-a6d0-bf37cc4f749e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>892225fa-5224-4a94-a1b5-b9b3fafe1f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email_id</value>
      <webElementGuid>581fc461-6292-4f31-8bb8-5eba1f63709d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email_id</value>
      <webElementGuid>271ea0eb-00b8-49c0-9008-3f9b834c6fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Email ID</value>
      <webElementGuid>9d42ce25-f93c-4f50-8de4-2071790d2257</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input email_id</value>
      <webElementGuid>034541bb-7431-4353-b2ac-c982491150d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email_id&quot;)</value>
      <webElementGuid>427e7122-6968-4419-ad0e-ad0ed80ad6ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email_id']</value>
      <webElementGuid>e58eced1-c0f1-4890-8a82-e913ecc4ce49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='proposer_details']/section/div/div/div[3]/div[2]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>e42475d3-0cfd-4dee-8e20-2b73c5800ecb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div/div/input</value>
      <webElementGuid>c94d27fc-6889-4a84-b438-f08c4e6b6cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @name = 'email_id' and @id = 'email_id' and @placeholder = 'Enter Email ID']</value>
      <webElementGuid>1ec50507-dd99-4df2-87be-97507b4629f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
