<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Brother</name>
   <tag></tag>
   <elementGuidId>9e21565a-8c8c-4944-8779-89c71bfba2f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='proposer_details']/section/div/div/div[6]/div[2]/div/div/div[2]/div/div/ul/li[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>32d34f61-7bd6-40fc-ab14-767072acbd95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>drop_element</value>
      <webElementGuid>b8d59ee2-3399-4765-8662-a59560500859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>BOTH</value>
      <webElementGuid>f36493a5-2574-41d4-98e9-6cb749f2becf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Brother</value>
      <webElementGuid>16af51bf-5f33-47bd-9e39-584478755273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;proposer_details&quot;)/section[@class=&quot;form_sec&quot;]/div[@class=&quot;custom_container&quot;]/div[@class=&quot;custom_container_dropdown&quot;]/div[@class=&quot;form_card&quot;]/div[@class=&quot;nominee nominee_in&quot;]/div[@class=&quot;accordion_common_content&quot;]/div[@class=&quot;form_flex&quot;]/div[@class=&quot;column&quot;]/div[@class=&quot;common_input quoteflow_drpdown&quot;]/div[@class=&quot;form_input borderdinput drop_cont relation_input relation_input_width in&quot;]/ul[@class=&quot;custom_drop_cont&quot;]/li[@class=&quot;drop_element&quot;]</value>
      <webElementGuid>6dd20bb3-4f74-4144-bb29-e0ff78730fdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='proposer_details']/section/div/div/div[6]/div[2]/div/div/div[2]/div/div/ul/li[5]</value>
      <webElementGuid>59cb5e84-ea26-4b6e-8aa4-aa6fdaf28232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mother'])[2]/following::li[1]</value>
      <webElementGuid>111fafc6-1f3f-465b-bf57-461faaa4ec4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Father'])[2]/following::li[2]</value>
      <webElementGuid>368c1f68-b685-40f9-96a2-70408c983403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sister'])[1]/preceding::li[1]</value>
      <webElementGuid>d7c65a95-89c4-4d23-a9de-ab4a3f0a268c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Son'])[2]/preceding::li[2]</value>
      <webElementGuid>9f4d8043-2ed6-4fa0-96aa-58437485233f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Brother']/parent::*</value>
      <webElementGuid>cd95460b-6a2a-4d05-b5f2-a93072486c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[5]</value>
      <webElementGuid>bc01e0b3-cf8c-4ffa-8c94-3ee0a5b0f412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Brother' or . = 'Brother')]</value>
      <webElementGuid>3999ed8c-ff8c-4169-808c-6387d6ab33cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
