<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_1</name>
   <tag></tag>
   <elementGuidId>4c0a75d2-a1bf-40bf-ac3e-e94c7a3eae1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.proposaltermscondition > label.checkbox > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[last()])[209]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3c7e4a01-d914-47fd-bcd0-954e55f225f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;health_questionnaire&quot;)/section[@class=&quot;form_sec new_questionnaire_styles filled&quot;]/div[@class=&quot;custom_container bg_ui filled&quot;]/div[@class=&quot;proposaltermscondition&quot;]/label[@class=&quot;checkbox&quot;]/span[1]</value>
      <webElementGuid>8dc639db-2f60-46a9-b9ef-c1cd4a9e8761</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='health_questionnaire']/section/div[4]/div/label/span</value>
      <webElementGuid>0026fd0e-1858-4708-862c-7400c490a100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/label/span</value>
      <webElementGuid>597c119d-99c6-4432-b9ac-55eb9dad1915</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
