<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span</name>
   <tag></tag>
   <elementGuidId>f2bf3f1a-030c-4848-9b1e-35bf411a1562</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.no_questionnaire.filled > div.checkbox_p > label.checkbox > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='health_questionnaire']/section/div[3]/div/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9d2bfef0-95a4-4b16-a914-b0afbb29e6ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;health_questionnaire&quot;)/section[@class=&quot;form_sec new_questionnaire_styles filled&quot;]/div[@class=&quot;custom_container bg_ui&quot;]/div[@class=&quot;no_questionnaire filled&quot;]/div[@class=&quot;checkbox_p&quot;]/label[@class=&quot;checkbox&quot;]/span[1]</value>
      <webElementGuid>add4272a-f562-4b47-a5b0-6a96336ad738</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='health_questionnaire']/section/div[3]/div/div/label/span</value>
      <webElementGuid>796d5808-3326-45f7-9e0b-8f462fed4520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[3]/div/div/label/span</value>
      <webElementGuid>9779e16d-3412-4a64-8cfd-a51113d0df2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
