<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Continue with detailed form to pay</name>
   <tag></tag>
   <elementGuidId>c3b08ce7-5bce-4448-893a-98cc7ce5af26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.link_brown</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='standardPaymentFlow();']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cfaafe86-6bd7-4843-a45e-c6d7a91b16d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>fbcc3da0-9262-43f3-9602-5e2e918c81fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>standardPaymentFlow();</value>
      <webElementGuid>b354bf78-fbb9-4612-b619-fdce4e69706e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link_brown</value>
      <webElementGuid>f81e6118-5cb9-4a15-aba8-aa3024d04e55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue with detailed form to pay</value>
      <webElementGuid>26a79d4d-9ddf-4e8f-9ad4-eb1de87d23f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quick-proposer-form&quot;)/div[@class=&quot;custom_container&quot;]/div[@class=&quot;center_checkbox&quot;]/div[@class=&quot;popup_btn_group&quot;]/div[@class=&quot;text-center&quot;]/a[@class=&quot;link_brown&quot;]</value>
      <webElementGuid>871876c1-5497-412d-a07b-f47d319b1311</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='standardPaymentFlow();']</value>
      <webElementGuid>8a5e92d6-7ae5-41f7-9dab-c368e44a0b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='quick-proposer-form']/div/div[2]/div/div/a</value>
      <webElementGuid>4468c315-8e97-4774-90e5-bda3764018fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Continue with detailed form to pay')]</value>
      <webElementGuid>d6ff9013-ce6e-465e-8e93-67a4c38c5bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::a[1]</value>
      <webElementGuid>af9c5811-23a8-48ab-8612-42ef5078392e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='back'])[1]/following::a[1]</value>
      <webElementGuid>b6bb5880-8d2a-4e68-9f9d-9f8ebf248ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[6]/preceding::a[1]</value>
      <webElementGuid>014fe83b-59d9-4559-88f9-32d28cd66b4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Proposal Summary'])[1]/preceding::a[1]</value>
      <webElementGuid>e0099fd4-5fb7-4fda-a8fe-e00122a3f08d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue with detailed form to pay']/parent::*</value>
      <webElementGuid>95ccf508-3e88-42e0-98ad-ba098b5500c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[9]</value>
      <webElementGuid>503aef79-f221-4c85-8866-2d0efde63251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a</value>
      <webElementGuid>618a7438-eb69-428f-b166-2081af8847c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = 'Continue with detailed form to pay' or . = 'Continue with detailed form to pay')]</value>
      <webElementGuid>e7c4788d-e209-4a3d-98d9-7c4417a12f9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
