<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AADHAR NO_aadhar_no</name>
   <tag></tag>
   <elementGuidId>6ffb8102-34b1-47c9-90f4-f8dbdc26704c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aadhar_no</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='aadhar_no']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d67fe776-8907-418c-83c4-5e2fb0e96560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>8d1c94b6-7c43-489a-89a9-71d98ff2bbed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>79f1bf17-9d84-4735-81d2-c8f86fd542f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>c516c9cc-81d7-45b9-90d2-f9b8489f6da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return isNumber(event,this,4);</value>
      <webElementGuid>ade3856e-32be-4a5a-9694-cb30534be7ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>return isNumber(event,this,4);</value>
      <webElementGuid>2ad94805-5204-4aee-bc48-949ac53100e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aadhar_no</value>
      <webElementGuid>dbda027e-aff0-4346-a446-ce0954294e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>aadhar_no</value>
      <webElementGuid>3eaa50fe-57b6-4fb0-8888-831c115a3b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Last 4 digits of Aadhar</value>
      <webElementGuid>cca80c68-be20-4ee7-b2ae-78970dda4793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input aadhar_no</value>
      <webElementGuid>31e3ce77-06f9-4e25-a656-a8c47ef1f232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kyc_container&quot;)/div[@class=&quot;kyc_details_cont adhar_card_details&quot;]/div[@class=&quot;kyc_details_wrapper&quot;]/div[@class=&quot;form_flex&quot;]/div[@class=&quot;column&quot;]/div[@class=&quot;common_input&quot;]/div[@class=&quot;form_input borderdinput focus_border&quot;]/div[@class=&quot;floating-label&quot;]/input[@id=&quot;aadhar_no&quot;]</value>
      <webElementGuid>5a057a5b-ec58-47f6-9526-0e8a71afad9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='aadhar_no']</value>
      <webElementGuid>88031590-0940-4384-813c-b051724b813b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kyc_container']/div[3]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>7e6c58e5-6773-40b4-93c9-ca98b16cc1df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/div/div/div/input</value>
      <webElementGuid>6cf89126-bf98-4f9a-ae2c-753384689947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'aadhar_no' and @name = 'aadhar_no' and @placeholder = 'Enter Last 4 digits of Aadhar']</value>
      <webElementGuid>239ad3b6-231e-413a-be0d-e275412f5e1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
