<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_last_name</name>
   <tag></tag>
   <elementGuidId>02c805ca-7bd9-4d2e-b993-e1f9f7a64a05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#last_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='last_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82de347b-70b2-473f-81d6-e73cca9e5005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c62d481a-5ab6-4fe6-b6a3-6ee81c1845e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>66b09729-f23b-43ce-8348-d2d640fbc116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>last_name</value>
      <webElementGuid>eae6ad95-775e-4461-a662-deecd2c742d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>last_name</value>
      <webElementGuid>d20a00c5-1dd2-4236-96c4-1ce399e8d9a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>3c35a5d8-961c-416d-ba8d-ca70b47e89b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>return validName(this);</value>
      <webElementGuid>84b4d5c2-b1b6-4045-a6e3-ecdd4a518c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type here</value>
      <webElementGuid>e510aa3d-62cb-4e7b-9c83-96ddd1a21f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input</value>
      <webElementGuid>b3096ca7-4b31-4d8d-ac96-66b8f4ca57b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quick-proposer-form&quot;)/div[@class=&quot;custom_container&quot;]/div[@class=&quot;custom_container_dropdown&quot;]/div[@class=&quot;form_card&quot;]/div[@class=&quot;form_flex&quot;]/div[@class=&quot;column&quot;]/div[@class=&quot;common_input&quot;]/div[@class=&quot;form_input borderdinput large_width&quot;]/div[@class=&quot;floating-label&quot;]/input[@id=&quot;last_name&quot;]</value>
      <webElementGuid>09fdd912-400d-4553-9837-11323c2ea65f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='last_name']</value>
      <webElementGuid>1bb7fe70-618c-4ef2-b548-0ab101195a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='quick-proposer-form']/div/div/div[3]/div[2]/div[3]/div/div/div/input</value>
      <webElementGuid>dcedd99f-ca04-4c79-9a8e-b94cb36cdd22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/div/div/input</value>
      <webElementGuid>9174a1eb-e129-4e6d-91de-ef7ce2aa2069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'last_name' and @id = 'last_name' and @placeholder = 'Type here']</value>
      <webElementGuid>1fa8e5e4-c9c6-4fae-97ec-9a60ac7544e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
