<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DATE OF BIRTH_aadhar_dob</name>
   <tag></tag>
   <elementGuidId>e67c92f6-e915-4c34-970f-88e7fafbf77d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aadhar_dob</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='aadhar_dob']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4ab4e9b5-7747-4b6e-b028-1e27377214e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>Off</value>
      <webElementGuid>8b92fcde-2f8f-4458-a1c9-fde586a1872c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb042899-d340-4ec1-9664-3acb84ed712e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aadhar_dob</value>
      <webElementGuid>28b6610d-69a5-4ec2-a5e1-3bd857a330c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>aadhar_dob</value>
      <webElementGuid>7da281fd-876d-473b-9835-9c78e3771fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>e55e8a7e-3618-4789-a5b5-78682a563bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DD / MM / YYYY</value>
      <webElementGuid>7cd7415c-3bf8-425a-9dd2-d7dee756ab6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>floating-input aadhar_dob</value>
      <webElementGuid>8f19b681-6dcd-4d3d-ac5c-91ba173e1297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kyc_container&quot;)/div[@class=&quot;kyc_details_cont adhar_card_details&quot;]/div[@class=&quot;kyc_details_wrapper&quot;]/div[@class=&quot;form_flex&quot;]/div[@class=&quot;column&quot;]/div[@class=&quot;common_input&quot;]/div[@class=&quot;form_input borderdinput&quot;]/div[@class=&quot;floating-label&quot;]/input[@id=&quot;aadhar_dob&quot;]</value>
      <webElementGuid>63ef39b9-548c-4f41-a628-0211034d77fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='aadhar_dob']</value>
      <webElementGuid>e6d258dd-6019-4212-bd77-62764cb9cc1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kyc_container']/div[3]/div/div/div[4]/div/div/div/input</value>
      <webElementGuid>e5d71590-b821-40ba-96d2-d6b0876b2c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[4]/div/div/div/input</value>
      <webElementGuid>b3a028a3-e48a-4b16-9981-0d4bd4b20a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'aadhar_dob' and @name = 'aadhar_dob' and @placeholder = 'DD / MM / YYYY']</value>
      <webElementGuid>015b848b-4172-4903-9a93-cd7617d5e0f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
